// Code generated by ent, DO NOT EDIT.

package visit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the visit type in the database.
	Label = "visit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldItineraryID holds the string denoting the itinerary_id field in the database.
	FieldItineraryID = "itinerary_id"
	// FieldPlaceID holds the string denoting the place_id field in the database.
	FieldPlaceID = "place_id"
	// FieldSequenceOrder holds the string denoting the sequence_order field in the database.
	FieldSequenceOrder = "sequence_order"
	// FieldPlannedDurationMinutes holds the string denoting the planned_duration_minutes field in the database.
	FieldPlannedDurationMinutes = "planned_duration_minutes"
	// FieldDistanceFromPreviousKm holds the string denoting the distance_from_previous_km field in the database.
	FieldDistanceFromPreviousKm = "distance_from_previous_km"
	// FieldTravelTimeFromPreviousMinutes holds the string denoting the travel_time_from_previous_minutes field in the database.
	FieldTravelTimeFromPreviousMinutes = "travel_time_from_previous_minutes"
	// FieldTransportMode holds the string denoting the transport_mode field in the database.
	FieldTransportMode = "transport_mode"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeItinerary holds the string denoting the itinerary edge name in mutations.
	EdgeItinerary = "itinerary"
	// EdgePlace holds the string denoting the place edge name in mutations.
	EdgePlace = "place"
	// Table holds the table name of the visit in the database.
	Table = "visits"
	// ItineraryTable is the table that holds the itinerary relation/edge.
	ItineraryTable = "visits"
	// ItineraryInverseTable is the table name for the Itinerary entity.
	// It exists in this package in order to avoid circular dependency with the "itinerary" package.
	ItineraryInverseTable = "itineraries"
	// ItineraryColumn is the table column denoting the itinerary relation/edge.
	ItineraryColumn = "itinerary_id"
	// PlaceTable is the table that holds the place relation/edge.
	PlaceTable = "visits"
	// PlaceInverseTable is the table name for the Place entity.
	// It exists in this package in order to avoid circular dependency with the "place" package.
	PlaceInverseTable = "places"
	// PlaceColumn is the table column denoting the place relation/edge.
	PlaceColumn = "place_id"
)

// Columns holds all SQL columns for visit fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldItineraryID,
	FieldPlaceID,
	FieldSequenceOrder,
	FieldPlannedDurationMinutes,
	FieldDistanceFromPreviousKm,
	FieldTravelTimeFromPreviousMinutes,
	FieldTransportMode,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ItineraryIDValidator is a validator for the "itinerary_id" field. It is called by the builders before save.
	ItineraryIDValidator func(string) error
	// PlaceIDValidator is a validator for the "place_id" field. It is called by the builders before save.
	PlaceIDValidator func(string) error
	// SequenceOrderValidator is a validator for the "sequence_order" field. It is called by the builders before save.
	SequenceOrderValidator func(int) error
	// DefaultPlannedDurationMinutes holds the default value on creation for the "planned_duration_minutes" field.
	DefaultPlannedDurationMinutes int
	// PlannedDurationMinutesValidator is a validator for the "planned_duration_minutes" field. It is called by the builders before save.
	PlannedDurationMinutesValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Visit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByItineraryID orders the results by the itinerary_id field.
func ByItineraryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItineraryID, opts...).ToFunc()
}

// ByPlaceID orders the results by the place_id field.
func ByPlaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaceID, opts...).ToFunc()
}

// BySequenceOrder orders the results by the sequence_order field.
func BySequenceOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequenceOrder, opts...).ToFunc()
}

// ByPlannedDurationMinutes orders the results by the planned_duration_minutes field.
func ByPlannedDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlannedDurationMinutes, opts...).ToFunc()
}

// ByDistanceFromPreviousKm orders the results by the distance_from_previous_km field.
func ByDistanceFromPreviousKm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistanceFromPreviousKm, opts...).ToFunc()
}

// ByTravelTimeFromPreviousMinutes orders the results by the travel_time_from_previous_minutes field.
func ByTravelTimeFromPreviousMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTravelTimeFromPreviousMinutes, opts...).ToFunc()
}

// ByTransportMode orders the results by the transport_mode field.
func ByTransportMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransportMode, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByItineraryField orders the results by itinerary field.
func ByItineraryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItineraryStep(), sql.OrderByField(field, opts...))
	}
}

// ByPlaceField orders the results by place field.
func ByPlaceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlaceStep(), sql.OrderByField(field, opts...))
	}
}
func newItineraryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItineraryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItineraryTable, ItineraryColumn),
	)
}
func newPlaceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlaceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlaceTable, PlaceColumn),
	)
}
