// Code generated by ent, DO NOT EDIT.

package visit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/omkar273/nashikdarshan/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUpdatedBy, v))
}

// ItineraryID applies equality check predicate on the "itinerary_id" field. It's identical to ItineraryIDEQ.
func ItineraryID(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldItineraryID, v))
}

// PlaceID applies equality check predicate on the "place_id" field. It's identical to PlaceIDEQ.
func PlaceID(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldPlaceID, v))
}

// SequenceOrder applies equality check predicate on the "sequence_order" field. It's identical to SequenceOrderEQ.
func SequenceOrder(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldSequenceOrder, v))
}

// PlannedDurationMinutes applies equality check predicate on the "planned_duration_minutes" field. It's identical to PlannedDurationMinutesEQ.
func PlannedDurationMinutes(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldPlannedDurationMinutes, v))
}

// DistanceFromPreviousKm applies equality check predicate on the "distance_from_previous_km" field. It's identical to DistanceFromPreviousKmEQ.
func DistanceFromPreviousKm(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldDistanceFromPreviousKm, v))
}

// TravelTimeFromPreviousMinutes applies equality check predicate on the "travel_time_from_previous_minutes" field. It's identical to TravelTimeFromPreviousMinutesEQ.
func TravelTimeFromPreviousMinutes(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldTravelTimeFromPreviousMinutes, v))
}

// TransportMode applies equality check predicate on the "transport_mode" field. It's identical to TransportModeEQ.
func TransportMode(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldTransportMode, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldNotes, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// ItineraryIDEQ applies the EQ predicate on the "itinerary_id" field.
func ItineraryIDEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldItineraryID, v))
}

// ItineraryIDNEQ applies the NEQ predicate on the "itinerary_id" field.
func ItineraryIDNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldItineraryID, v))
}

// ItineraryIDIn applies the In predicate on the "itinerary_id" field.
func ItineraryIDIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldItineraryID, vs...))
}

// ItineraryIDNotIn applies the NotIn predicate on the "itinerary_id" field.
func ItineraryIDNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldItineraryID, vs...))
}

// ItineraryIDGT applies the GT predicate on the "itinerary_id" field.
func ItineraryIDGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldItineraryID, v))
}

// ItineraryIDGTE applies the GTE predicate on the "itinerary_id" field.
func ItineraryIDGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldItineraryID, v))
}

// ItineraryIDLT applies the LT predicate on the "itinerary_id" field.
func ItineraryIDLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldItineraryID, v))
}

// ItineraryIDLTE applies the LTE predicate on the "itinerary_id" field.
func ItineraryIDLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldItineraryID, v))
}

// ItineraryIDContains applies the Contains predicate on the "itinerary_id" field.
func ItineraryIDContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldItineraryID, v))
}

// ItineraryIDHasPrefix applies the HasPrefix predicate on the "itinerary_id" field.
func ItineraryIDHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldItineraryID, v))
}

// ItineraryIDHasSuffix applies the HasSuffix predicate on the "itinerary_id" field.
func ItineraryIDHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldItineraryID, v))
}

// ItineraryIDEqualFold applies the EqualFold predicate on the "itinerary_id" field.
func ItineraryIDEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldItineraryID, v))
}

// ItineraryIDContainsFold applies the ContainsFold predicate on the "itinerary_id" field.
func ItineraryIDContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldItineraryID, v))
}

// PlaceIDEQ applies the EQ predicate on the "place_id" field.
func PlaceIDEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldPlaceID, v))
}

// PlaceIDNEQ applies the NEQ predicate on the "place_id" field.
func PlaceIDNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldPlaceID, v))
}

// PlaceIDIn applies the In predicate on the "place_id" field.
func PlaceIDIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldPlaceID, vs...))
}

// PlaceIDNotIn applies the NotIn predicate on the "place_id" field.
func PlaceIDNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldPlaceID, vs...))
}

// PlaceIDGT applies the GT predicate on the "place_id" field.
func PlaceIDGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldPlaceID, v))
}

// PlaceIDGTE applies the GTE predicate on the "place_id" field.
func PlaceIDGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldPlaceID, v))
}

// PlaceIDLT applies the LT predicate on the "place_id" field.
func PlaceIDLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldPlaceID, v))
}

// PlaceIDLTE applies the LTE predicate on the "place_id" field.
func PlaceIDLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldPlaceID, v))
}

// PlaceIDContains applies the Contains predicate on the "place_id" field.
func PlaceIDContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldPlaceID, v))
}

// PlaceIDHasPrefix applies the HasPrefix predicate on the "place_id" field.
func PlaceIDHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldPlaceID, v))
}

// PlaceIDHasSuffix applies the HasSuffix predicate on the "place_id" field.
func PlaceIDHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldPlaceID, v))
}

// PlaceIDEqualFold applies the EqualFold predicate on the "place_id" field.
func PlaceIDEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldPlaceID, v))
}

// PlaceIDContainsFold applies the ContainsFold predicate on the "place_id" field.
func PlaceIDContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldPlaceID, v))
}

// SequenceOrderEQ applies the EQ predicate on the "sequence_order" field.
func SequenceOrderEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldSequenceOrder, v))
}

// SequenceOrderNEQ applies the NEQ predicate on the "sequence_order" field.
func SequenceOrderNEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldSequenceOrder, v))
}

// SequenceOrderIn applies the In predicate on the "sequence_order" field.
func SequenceOrderIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldSequenceOrder, vs...))
}

// SequenceOrderNotIn applies the NotIn predicate on the "sequence_order" field.
func SequenceOrderNotIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldSequenceOrder, vs...))
}

// SequenceOrderGT applies the GT predicate on the "sequence_order" field.
func SequenceOrderGT(v int) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldSequenceOrder, v))
}

// SequenceOrderGTE applies the GTE predicate on the "sequence_order" field.
func SequenceOrderGTE(v int) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldSequenceOrder, v))
}

// SequenceOrderLT applies the LT predicate on the "sequence_order" field.
func SequenceOrderLT(v int) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldSequenceOrder, v))
}

// SequenceOrderLTE applies the LTE predicate on the "sequence_order" field.
func SequenceOrderLTE(v int) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldSequenceOrder, v))
}

// PlannedDurationMinutesEQ applies the EQ predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldPlannedDurationMinutes, v))
}

// PlannedDurationMinutesNEQ applies the NEQ predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesNEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldPlannedDurationMinutes, v))
}

// PlannedDurationMinutesIn applies the In predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldPlannedDurationMinutes, vs...))
}

// PlannedDurationMinutesNotIn applies the NotIn predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesNotIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldPlannedDurationMinutes, vs...))
}

// PlannedDurationMinutesGT applies the GT predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesGT(v int) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldPlannedDurationMinutes, v))
}

// PlannedDurationMinutesGTE applies the GTE predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesGTE(v int) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldPlannedDurationMinutes, v))
}

// PlannedDurationMinutesLT applies the LT predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesLT(v int) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldPlannedDurationMinutes, v))
}

// PlannedDurationMinutesLTE applies the LTE predicate on the "planned_duration_minutes" field.
func PlannedDurationMinutesLTE(v int) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldPlannedDurationMinutes, v))
}

// DistanceFromPreviousKmEQ applies the EQ predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmEQ(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldDistanceFromPreviousKm, v))
}

// DistanceFromPreviousKmNEQ applies the NEQ predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmNEQ(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldDistanceFromPreviousKm, v))
}

// DistanceFromPreviousKmIn applies the In predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmIn(vs ...float64) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldDistanceFromPreviousKm, vs...))
}

// DistanceFromPreviousKmNotIn applies the NotIn predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmNotIn(vs ...float64) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldDistanceFromPreviousKm, vs...))
}

// DistanceFromPreviousKmGT applies the GT predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmGT(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldDistanceFromPreviousKm, v))
}

// DistanceFromPreviousKmGTE applies the GTE predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmGTE(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldDistanceFromPreviousKm, v))
}

// DistanceFromPreviousKmLT applies the LT predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmLT(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldDistanceFromPreviousKm, v))
}

// DistanceFromPreviousKmLTE applies the LTE predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmLTE(v float64) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldDistanceFromPreviousKm, v))
}

// DistanceFromPreviousKmIsNil applies the IsNil predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldDistanceFromPreviousKm))
}

// DistanceFromPreviousKmNotNil applies the NotNil predicate on the "distance_from_previous_km" field.
func DistanceFromPreviousKmNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldDistanceFromPreviousKm))
}

// TravelTimeFromPreviousMinutesEQ applies the EQ predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldTravelTimeFromPreviousMinutes, v))
}

// TravelTimeFromPreviousMinutesNEQ applies the NEQ predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesNEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldTravelTimeFromPreviousMinutes, v))
}

// TravelTimeFromPreviousMinutesIn applies the In predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldTravelTimeFromPreviousMinutes, vs...))
}

// TravelTimeFromPreviousMinutesNotIn applies the NotIn predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesNotIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldTravelTimeFromPreviousMinutes, vs...))
}

// TravelTimeFromPreviousMinutesGT applies the GT predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesGT(v int) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldTravelTimeFromPreviousMinutes, v))
}

// TravelTimeFromPreviousMinutesGTE applies the GTE predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesGTE(v int) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldTravelTimeFromPreviousMinutes, v))
}

// TravelTimeFromPreviousMinutesLT applies the LT predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesLT(v int) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldTravelTimeFromPreviousMinutes, v))
}

// TravelTimeFromPreviousMinutesLTE applies the LTE predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesLTE(v int) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldTravelTimeFromPreviousMinutes, v))
}

// TravelTimeFromPreviousMinutesIsNil applies the IsNil predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldTravelTimeFromPreviousMinutes))
}

// TravelTimeFromPreviousMinutesNotNil applies the NotNil predicate on the "travel_time_from_previous_minutes" field.
func TravelTimeFromPreviousMinutesNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldTravelTimeFromPreviousMinutes))
}

// TransportModeEQ applies the EQ predicate on the "transport_mode" field.
func TransportModeEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldTransportMode, v))
}

// TransportModeNEQ applies the NEQ predicate on the "transport_mode" field.
func TransportModeNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldTransportMode, v))
}

// TransportModeIn applies the In predicate on the "transport_mode" field.
func TransportModeIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldTransportMode, vs...))
}

// TransportModeNotIn applies the NotIn predicate on the "transport_mode" field.
func TransportModeNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldTransportMode, vs...))
}

// TransportModeGT applies the GT predicate on the "transport_mode" field.
func TransportModeGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldTransportMode, v))
}

// TransportModeGTE applies the GTE predicate on the "transport_mode" field.
func TransportModeGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldTransportMode, v))
}

// TransportModeLT applies the LT predicate on the "transport_mode" field.
func TransportModeLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldTransportMode, v))
}

// TransportModeLTE applies the LTE predicate on the "transport_mode" field.
func TransportModeLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldTransportMode, v))
}

// TransportModeContains applies the Contains predicate on the "transport_mode" field.
func TransportModeContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldTransportMode, v))
}

// TransportModeHasPrefix applies the HasPrefix predicate on the "transport_mode" field.
func TransportModeHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldTransportMode, v))
}

// TransportModeHasSuffix applies the HasSuffix predicate on the "transport_mode" field.
func TransportModeHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldTransportMode, v))
}

// TransportModeIsNil applies the IsNil predicate on the "transport_mode" field.
func TransportModeIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldTransportMode))
}

// TransportModeNotNil applies the NotNil predicate on the "transport_mode" field.
func TransportModeNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldTransportMode))
}

// TransportModeEqualFold applies the EqualFold predicate on the "transport_mode" field.
func TransportModeEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldTransportMode, v))
}

// TransportModeContainsFold applies the ContainsFold predicate on the "transport_mode" field.
func TransportModeContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldTransportMode, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldNotes, v))
}

// HasItinerary applies the HasEdge predicate on the "itinerary" edge.
func HasItinerary() predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItineraryTable, ItineraryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItineraryWith applies the HasEdge predicate on the "itinerary" edge with a given conditions (other predicates).
func HasItineraryWith(preds ...predicate.Itinerary) predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := newItineraryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlace applies the HasEdge predicate on the "place" edge.
func HasPlace() predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlaceTable, PlaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaceWith applies the HasEdge predicate on the "place" edge with a given conditions (other predicates).
func HasPlaceWith(preds ...predicate.Place) predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := newPlaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Visit) predicate.Visit {
	return predicate.Visit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Visit) predicate.Visit {
	return predicate.Visit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Visit) predicate.Visit {
	return predicate.Visit(sql.NotPredicates(p))
}
