// Code generated by ent, DO NOT EDIT.

package eventoccurrence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the eventoccurrence type in the database.
	Label = "event_occurrence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldRecurrenceType holds the string denoting the recurrence_type field in the database.
	FieldRecurrenceType = "recurrence_type"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldDurationMinutes holds the string denoting the duration_minutes field in the database.
	FieldDurationMinutes = "duration_minutes"
	// FieldDayOfWeek holds the string denoting the day_of_week field in the database.
	FieldDayOfWeek = "day_of_week"
	// FieldDayOfMonth holds the string denoting the day_of_month field in the database.
	FieldDayOfMonth = "day_of_month"
	// FieldMonthOfYear holds the string denoting the month_of_year field in the database.
	FieldMonthOfYear = "month_of_year"
	// FieldExceptionDates holds the string denoting the exception_dates field in the database.
	FieldExceptionDates = "exception_dates"
	// EdgeEvent holds the string denoting the event edge name in mutations.
	EdgeEvent = "event"
	// Table holds the table name of the eventoccurrence in the database.
	Table = "event_occurrences"
	// EventTable is the table that holds the event relation/edge.
	EventTable = "event_occurrences"
	// EventInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventInverseTable = "events"
	// EventColumn is the table column denoting the event relation/edge.
	EventColumn = "event_id"
)

// Columns holds all SQL columns for eventoccurrence fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldMetadata,
	FieldEventID,
	FieldRecurrenceType,
	FieldStartTime,
	FieldEndTime,
	FieldDurationMinutes,
	FieldDayOfWeek,
	FieldDayOfMonth,
	FieldMonthOfYear,
	FieldExceptionDates,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]string
	// EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	EventIDValidator func(string) error
	// RecurrenceTypeValidator is a validator for the "recurrence_type" field. It is called by the builders before save.
	RecurrenceTypeValidator func(string) error
	// DayOfWeekValidator is a validator for the "day_of_week" field. It is called by the builders before save.
	DayOfWeekValidator func(int) error
	// DayOfMonthValidator is a validator for the "day_of_month" field. It is called by the builders before save.
	DayOfMonthValidator func(int) error
	// MonthOfYearValidator is a validator for the "month_of_year" field. It is called by the builders before save.
	MonthOfYearValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the EventOccurrence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByRecurrenceType orders the results by the recurrence_type field.
func ByRecurrenceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecurrenceType, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByDurationMinutes orders the results by the duration_minutes field.
func ByDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMinutes, opts...).ToFunc()
}

// ByDayOfWeek orders the results by the day_of_week field.
func ByDayOfWeek(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDayOfWeek, opts...).ToFunc()
}

// ByDayOfMonth orders the results by the day_of_month field.
func ByDayOfMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDayOfMonth, opts...).ToFunc()
}

// ByMonthOfYear orders the results by the month_of_year field.
func ByMonthOfYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthOfYear, opts...).ToFunc()
}

// ByEventField orders the results by event field.
func ByEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventStep(), sql.OrderByField(field, opts...))
	}
}
func newEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
	)
}
