// Code generated by ent, DO NOT EDIT.

package eventexception

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/omkar273/nashikdarshan/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EventException {
	return predicate.EventException(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EventException {
	return predicate.EventException(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EventException {
	return predicate.EventException(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EventException {
	return predicate.EventException(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EventException {
	return predicate.EventException(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EventException {
	return predicate.EventException(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EventException {
	return predicate.EventException(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EventException {
	return predicate.EventException(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EventException {
	return predicate.EventException(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EventException {
	return predicate.EventException(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EventException {
	return predicate.EventException(sql.FieldContainsFold(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.EventException {
	return predicate.EventException(sql.FieldEQ(FieldEventID, v))
}

// OccurrenceStartAt applies equality check predicate on the "occurrence_start_at" field. It's identical to OccurrenceStartAtEQ.
func OccurrenceStartAt(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldEQ(FieldOccurrenceStartAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.EventException {
	return predicate.EventException(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.EventException {
	return predicate.EventException(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.EventException {
	return predicate.EventException(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.EventException {
	return predicate.EventException(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.EventException {
	return predicate.EventException(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.EventException {
	return predicate.EventException(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.EventException {
	return predicate.EventException(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.EventException {
	return predicate.EventException(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.EventException {
	return predicate.EventException(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.EventException {
	return predicate.EventException(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.EventException {
	return predicate.EventException(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.EventException {
	return predicate.EventException(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.EventException {
	return predicate.EventException(sql.FieldContainsFold(FieldEventID, v))
}

// OccurrenceStartAtEQ applies the EQ predicate on the "occurrence_start_at" field.
func OccurrenceStartAtEQ(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldEQ(FieldOccurrenceStartAt, v))
}

// OccurrenceStartAtNEQ applies the NEQ predicate on the "occurrence_start_at" field.
func OccurrenceStartAtNEQ(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldNEQ(FieldOccurrenceStartAt, v))
}

// OccurrenceStartAtIn applies the In predicate on the "occurrence_start_at" field.
func OccurrenceStartAtIn(vs ...time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldIn(FieldOccurrenceStartAt, vs...))
}

// OccurrenceStartAtNotIn applies the NotIn predicate on the "occurrence_start_at" field.
func OccurrenceStartAtNotIn(vs ...time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldNotIn(FieldOccurrenceStartAt, vs...))
}

// OccurrenceStartAtGT applies the GT predicate on the "occurrence_start_at" field.
func OccurrenceStartAtGT(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldGT(FieldOccurrenceStartAt, v))
}

// OccurrenceStartAtGTE applies the GTE predicate on the "occurrence_start_at" field.
func OccurrenceStartAtGTE(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldGTE(FieldOccurrenceStartAt, v))
}

// OccurrenceStartAtLT applies the LT predicate on the "occurrence_start_at" field.
func OccurrenceStartAtLT(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldLT(FieldOccurrenceStartAt, v))
}

// OccurrenceStartAtLTE applies the LTE predicate on the "occurrence_start_at" field.
func OccurrenceStartAtLTE(v time.Time) predicate.EventException {
	return predicate.EventException(sql.FieldLTE(FieldOccurrenceStartAt, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.EventException {
	return predicate.EventException(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.EventException {
	return predicate.EventException(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventException) predicate.EventException {
	return predicate.EventException(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventException) predicate.EventException {
	return predicate.EventException(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventException) predicate.EventException {
	return predicate.EventException(sql.NotPredicates(p))
}
