// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/nashikdarshan/ent/event"
	"github.com/omkar273/nashikdarshan/ent/eventoccurrence"
	"github.com/omkar273/nashikdarshan/ent/predicate"
	"github.com/shopspring/decimal"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventUpdate) SetStatus(v string) *EventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventUpdate) SetNillableStatus(v *string) *EventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdate) SetUpdatedAt(v time.Time) *EventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EventUpdate) SetUpdatedBy(v string) *EventUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUpdatedBy(v *string) *EventUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *EventUpdate) ClearUpdatedBy() *EventUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EventUpdate) SetMetadata(v map[string]string) *EventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *EventUpdate) ClearMetadata() *EventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetType sets the "type" field.
func (_u *EventUpdate) SetType(v string) *EventUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableType(v *string) *EventUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *EventUpdate) SetTitle(v string) *EventUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTitle(v *string) *EventUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *EventUpdate) SetSubtitle(v string) *EventUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSubtitle(v *string) *EventUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *EventUpdate) ClearSubtitle() *EventUpdate {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdate) SetDescription(v string) *EventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDescription(v *string) *EventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EventUpdate) ClearDescription() *EventUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlaceID sets the "place_id" field.
func (_u *EventUpdate) SetPlaceID(v string) *EventUpdate {
	_u.mutation.SetPlaceID(v)
	return _u
}

// SetNillablePlaceID sets the "place_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePlaceID(v *string) *EventUpdate {
	if v != nil {
		_u.SetPlaceID(*v)
	}
	return _u
}

// ClearPlaceID clears the value of the "place_id" field.
func (_u *EventUpdate) ClearPlaceID() *EventUpdate {
	_u.mutation.ClearPlaceID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *EventUpdate) SetStartDate(v time.Time) *EventUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *EventUpdate) SetNillableStartDate(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *EventUpdate) SetEndDate(v time.Time) *EventUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *EventUpdate) SetNillableEndDate(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *EventUpdate) ClearEndDate() *EventUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *EventUpdate) SetCoverImageURL(v string) *EventUpdate {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *EventUpdate) SetNillableCoverImageURL(v *string) *EventUpdate {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *EventUpdate) ClearCoverImageURL() *EventUpdate {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetImages sets the "images" field.
func (_u *EventUpdate) SetImages(v []string) *EventUpdate {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *EventUpdate) AppendImages(v []string) *EventUpdate {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *EventUpdate) ClearImages() *EventUpdate {
	_u.mutation.ClearImages()
	return _u
}

// SetTags sets the "tags" field.
func (_u *EventUpdate) SetTags(v []string) *EventUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *EventUpdate) AppendTags(v []string) *EventUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *EventUpdate) ClearTags() *EventUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *EventUpdate) SetLatitude(v *decimal.Decimal) *EventUpdate {
	_u.mutation.SetLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *EventUpdate) ClearLatitude() *EventUpdate {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *EventUpdate) SetLongitude(v *decimal.Decimal) *EventUpdate {
	_u.mutation.SetLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *EventUpdate) ClearLongitude() *EventUpdate {
	_u.mutation.ClearLongitude()
	return _u
}

// SetLocationName sets the "location_name" field.
func (_u *EventUpdate) SetLocationName(v string) *EventUpdate {
	_u.mutation.SetLocationName(v)
	return _u
}

// SetNillableLocationName sets the "location_name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableLocationName(v *string) *EventUpdate {
	if v != nil {
		_u.SetLocationName(*v)
	}
	return _u
}

// ClearLocationName clears the value of the "location_name" field.
func (_u *EventUpdate) ClearLocationName() *EventUpdate {
	_u.mutation.ClearLocationName()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *EventUpdate) SetViewCount(v int) *EventUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *EventUpdate) SetNillableViewCount(v *int) *EventUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *EventUpdate) AddViewCount(v int) *EventUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetInterestedCount sets the "interested_count" field.
func (_u *EventUpdate) SetInterestedCount(v int) *EventUpdate {
	_u.mutation.ResetInterestedCount()
	_u.mutation.SetInterestedCount(v)
	return _u
}

// SetNillableInterestedCount sets the "interested_count" field if the given value is not nil.
func (_u *EventUpdate) SetNillableInterestedCount(v *int) *EventUpdate {
	if v != nil {
		_u.SetInterestedCount(*v)
	}
	return _u
}

// AddInterestedCount adds value to the "interested_count" field.
func (_u *EventUpdate) AddInterestedCount(v int) *EventUpdate {
	_u.mutation.AddInterestedCount(v)
	return _u
}

// AddOccurrenceIDs adds the "occurrences" edge to the EventOccurrence entity by IDs.
func (_u *EventUpdate) AddOccurrenceIDs(ids ...string) *EventUpdate {
	_u.mutation.AddOccurrenceIDs(ids...)
	return _u
}

// AddOccurrences adds the "occurrences" edges to the EventOccurrence entity.
func (_u *EventUpdate) AddOccurrences(v ...*EventOccurrence) *EventUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOccurrenceIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// ClearOccurrences clears all "occurrences" edges to the EventOccurrence entity.
func (_u *EventUpdate) ClearOccurrences() *EventUpdate {
	_u.mutation.ClearOccurrences()
	return _u
}

// RemoveOccurrenceIDs removes the "occurrences" edge to EventOccurrence entities by IDs.
func (_u *EventUpdate) RemoveOccurrenceIDs(ids ...string) *EventUpdate {
	_u.mutation.RemoveOccurrenceIDs(ids...)
	return _u
}

// RemoveOccurrences removes "occurrences" edges to EventOccurrence entities.
func (_u *EventUpdate) RemoveOccurrences(v ...*EventOccurrence) *EventUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOccurrenceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := event.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := event.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := event.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Event.subtitle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocationName(); ok {
		if err := event.LocationNameValidator(v); err != nil {
			return &ValidationError{Name: "location_name", err: fmt.Errorf(`ent: validator failed for field "Event.location_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := event.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Event.view_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InterestedCount(); ok {
		if err := event.InterestedCountValidator(v); err != nil {
			return &ValidationError{Name: "interested_count", err: fmt.Errorf(`ent: validator failed for field "Event.interested_count": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(event.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(event.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(event.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(event.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(event.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(event.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(event.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(event.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PlaceID(); ok {
		_spec.SetField(event.FieldPlaceID, field.TypeString, value)
	}
	if _u.mutation.PlaceIDCleared() {
		_spec.ClearField(event.FieldPlaceID, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(event.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(event.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(event.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(event.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(event.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(event.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(event.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(event.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(event.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(event.FieldLatitude, field.TypeOther, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(event.FieldLatitude, field.TypeOther)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(event.FieldLongitude, field.TypeOther, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(event.FieldLongitude, field.TypeOther)
	}
	if value, ok := _u.mutation.LocationName(); ok {
		_spec.SetField(event.FieldLocationName, field.TypeString, value)
	}
	if _u.mutation.LocationNameCleared() {
		_spec.ClearField(event.FieldLocationName, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(event.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(event.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InterestedCount(); ok {
		_spec.SetField(event.FieldInterestedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInterestedCount(); ok {
		_spec.AddField(event.FieldInterestedCount, field.TypeInt, value)
	}
	if _u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOccurrencesIDs(); len(nodes) > 0 && !_u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetStatus sets the "status" field.
func (_u *EventUpdateOne) SetStatus(v string) *EventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableStatus(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdateOne) SetUpdatedAt(v time.Time) *EventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EventUpdateOne) SetUpdatedBy(v string) *EventUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUpdatedBy(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *EventUpdateOne) ClearUpdatedBy() *EventUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EventUpdateOne) SetMetadata(v map[string]string) *EventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *EventUpdateOne) ClearMetadata() *EventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetType sets the "type" field.
func (_u *EventUpdateOne) SetType(v string) *EventUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableType(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *EventUpdateOne) SetTitle(v string) *EventUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTitle(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *EventUpdateOne) SetSubtitle(v string) *EventUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSubtitle(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *EventUpdateOne) ClearSubtitle() *EventUpdateOne {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdateOne) SetDescription(v string) *EventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDescription(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EventUpdateOne) ClearDescription() *EventUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlaceID sets the "place_id" field.
func (_u *EventUpdateOne) SetPlaceID(v string) *EventUpdateOne {
	_u.mutation.SetPlaceID(v)
	return _u
}

// SetNillablePlaceID sets the "place_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePlaceID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPlaceID(*v)
	}
	return _u
}

// ClearPlaceID clears the value of the "place_id" field.
func (_u *EventUpdateOne) ClearPlaceID() *EventUpdateOne {
	_u.mutation.ClearPlaceID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *EventUpdateOne) SetStartDate(v time.Time) *EventUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableStartDate(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *EventUpdateOne) SetEndDate(v time.Time) *EventUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableEndDate(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *EventUpdateOne) ClearEndDate() *EventUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *EventUpdateOne) SetCoverImageURL(v string) *EventUpdateOne {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableCoverImageURL(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *EventUpdateOne) ClearCoverImageURL() *EventUpdateOne {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetImages sets the "images" field.
func (_u *EventUpdateOne) SetImages(v []string) *EventUpdateOne {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *EventUpdateOne) AppendImages(v []string) *EventUpdateOne {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *EventUpdateOne) ClearImages() *EventUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// SetTags sets the "tags" field.
func (_u *EventUpdateOne) SetTags(v []string) *EventUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *EventUpdateOne) AppendTags(v []string) *EventUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *EventUpdateOne) ClearTags() *EventUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *EventUpdateOne) SetLatitude(v *decimal.Decimal) *EventUpdateOne {
	_u.mutation.SetLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *EventUpdateOne) ClearLatitude() *EventUpdateOne {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *EventUpdateOne) SetLongitude(v *decimal.Decimal) *EventUpdateOne {
	_u.mutation.SetLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *EventUpdateOne) ClearLongitude() *EventUpdateOne {
	_u.mutation.ClearLongitude()
	return _u
}

// SetLocationName sets the "location_name" field.
func (_u *EventUpdateOne) SetLocationName(v string) *EventUpdateOne {
	_u.mutation.SetLocationName(v)
	return _u
}

// SetNillableLocationName sets the "location_name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableLocationName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetLocationName(*v)
	}
	return _u
}

// ClearLocationName clears the value of the "location_name" field.
func (_u *EventUpdateOne) ClearLocationName() *EventUpdateOne {
	_u.mutation.ClearLocationName()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *EventUpdateOne) SetViewCount(v int) *EventUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableViewCount(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *EventUpdateOne) AddViewCount(v int) *EventUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetInterestedCount sets the "interested_count" field.
func (_u *EventUpdateOne) SetInterestedCount(v int) *EventUpdateOne {
	_u.mutation.ResetInterestedCount()
	_u.mutation.SetInterestedCount(v)
	return _u
}

// SetNillableInterestedCount sets the "interested_count" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableInterestedCount(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetInterestedCount(*v)
	}
	return _u
}

// AddInterestedCount adds value to the "interested_count" field.
func (_u *EventUpdateOne) AddInterestedCount(v int) *EventUpdateOne {
	_u.mutation.AddInterestedCount(v)
	return _u
}

// AddOccurrenceIDs adds the "occurrences" edge to the EventOccurrence entity by IDs.
func (_u *EventUpdateOne) AddOccurrenceIDs(ids ...string) *EventUpdateOne {
	_u.mutation.AddOccurrenceIDs(ids...)
	return _u
}

// AddOccurrences adds the "occurrences" edges to the EventOccurrence entity.
func (_u *EventUpdateOne) AddOccurrences(v ...*EventOccurrence) *EventUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOccurrenceIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// ClearOccurrences clears all "occurrences" edges to the EventOccurrence entity.
func (_u *EventUpdateOne) ClearOccurrences() *EventUpdateOne {
	_u.mutation.ClearOccurrences()
	return _u
}

// RemoveOccurrenceIDs removes the "occurrences" edge to EventOccurrence entities by IDs.
func (_u *EventUpdateOne) RemoveOccurrenceIDs(ids ...string) *EventUpdateOne {
	_u.mutation.RemoveOccurrenceIDs(ids...)
	return _u
}

// RemoveOccurrences removes "occurrences" edges to EventOccurrence entities.
func (_u *EventUpdateOne) RemoveOccurrences(v ...*EventOccurrence) *EventUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOccurrenceIDs(ids...)
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := event.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := event.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := event.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Event.subtitle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocationName(); ok {
		if err := event.LocationNameValidator(v); err != nil {
			return &ValidationError{Name: "location_name", err: fmt.Errorf(`ent: validator failed for field "Event.location_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := event.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Event.view_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InterestedCount(); ok {
		if err := event.InterestedCountValidator(v); err != nil {
			return &ValidationError{Name: "interested_count", err: fmt.Errorf(`ent: validator failed for field "Event.interested_count": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(event.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(event.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(event.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(event.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(event.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(event.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(event.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(event.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PlaceID(); ok {
		_spec.SetField(event.FieldPlaceID, field.TypeString, value)
	}
	if _u.mutation.PlaceIDCleared() {
		_spec.ClearField(event.FieldPlaceID, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(event.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(event.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(event.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(event.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(event.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(event.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(event.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(event.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(event.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(event.FieldLatitude, field.TypeOther, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(event.FieldLatitude, field.TypeOther)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(event.FieldLongitude, field.TypeOther, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(event.FieldLongitude, field.TypeOther)
	}
	if value, ok := _u.mutation.LocationName(); ok {
		_spec.SetField(event.FieldLocationName, field.TypeString, value)
	}
	if _u.mutation.LocationNameCleared() {
		_spec.ClearField(event.FieldLocationName, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(event.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(event.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InterestedCount(); ok {
		_spec.SetField(event.FieldInterestedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInterestedCount(); ok {
		_spec.AddField(event.FieldInterestedCount, field.TypeInt, value)
	}
	if _u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOccurrencesIDs(); len(nodes) > 0 && !_u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
