// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/nashikdarshan/ent/event"
	"github.com/omkar273/nashikdarshan/ent/eventoverride"
)

// EventOverride is the model entity for the EventOverride schema.
type EventOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// Start of the occurrence being moved
	OriginalStartAt time.Time `json:"original_start_at,omitempty"`
	// NewStartAt holds the value of the "new_start_at" field.
	NewStartAt time.Time `json:"new_start_at,omitempty"`
	// NewEndAt holds the value of the "new_end_at" field.
	NewEndAt time.Time `json:"new_end_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventOverrideQuery when eager-loading is set.
	Edges        EventOverrideEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventOverrideEdges holds the relations/edges for other nodes in the graph.
type EventOverrideEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventOverrideEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventoverride.FieldID, eventoverride.FieldEventID:
			values[i] = new(sql.NullString)
		case eventoverride.FieldOriginalStartAt, eventoverride.FieldNewStartAt, eventoverride.FieldNewEndAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventOverride fields.
func (_m *EventOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventoverride.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case eventoverride.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.String
			}
		case eventoverride.FieldOriginalStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field original_start_at", values[i])
			} else if value.Valid {
				_m.OriginalStartAt = value.Time
			}
		case eventoverride.FieldNewStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field new_start_at", values[i])
			} else if value.Valid {
				_m.NewStartAt = value.Time
			}
		case eventoverride.FieldNewEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field new_end_at", values[i])
			} else if value.Valid {
				_m.NewEndAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventOverride.
// This includes values selected through modifiers, order, etc.
func (_m *EventOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the EventOverride entity.
func (_m *EventOverride) QueryEvent() *EventQuery {
	return NewEventOverrideClient(_m.config).QueryEvent(_m)
}

// Update returns a builder for updating this EventOverride.
// Note that you need to call EventOverride.Unwrap() before calling this method if this EventOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EventOverride) Update() *EventOverrideUpdateOne {
	return NewEventOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EventOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EventOverride) Unwrap() *EventOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EventOverride) String() string {
	var builder strings.Builder
	builder.WriteString("EventOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(_m.EventID)
	builder.WriteString(", ")
	builder.WriteString("original_start_at=")
	builder.WriteString(_m.OriginalStartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("new_start_at=")
	builder.WriteString(_m.NewStartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("new_end_at=")
	builder.WriteString(_m.NewEndAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EventOverrides is a parsable slice of EventOverride.
type EventOverrides []*EventOverride
