// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/nashikdarshan/ent/event"
	"github.com/omkar273/nashikdarshan/ent/eventexception"
	"github.com/omkar273/nashikdarshan/ent/eventoverride"
	"github.com/omkar273/nashikdarshan/ent/place"
	"github.com/omkar273/nashikdarshan/internal/types"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *EventCreate) SetStatus(v string) *EventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventCreate) SetNillableStatus(v *string) *EventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventCreate) SetCreatedAt(v time.Time) *EventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventCreate) SetUpdatedAt(v time.Time) *EventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EventCreate) SetCreatedBy(v string) *EventCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedBy(v *string) *EventCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *EventCreate) SetUpdatedBy(v string) *EventCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedBy(v *string) *EventCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *EventCreate) SetMetadata(v map[string]string) *EventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetPlaceID sets the "place_id" field.
func (_c *EventCreate) SetPlaceID(v string) *EventCreate {
	_c.mutation.SetPlaceID(v)
	return _c
}

// SetNillablePlaceID sets the "place_id" field if the given value is not nil.
func (_c *EventCreate) SetNillablePlaceID(v *string) *EventCreate {
	if v != nil {
		_c.SetPlaceID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *EventCreate) SetTitle(v string) *EventCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *EventCreate) SetSubtitle(v string) *EventCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_c *EventCreate) SetNillableSubtitle(v *string) *EventCreate {
	if v != nil {
		_c.SetSubtitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *EventCreate) SetDescription(v string) *EventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EventCreate) SetNillableDescription(v *string) *EventCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *EventCreate) SetStartAt(v time.Time) *EventCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *EventCreate) SetEndAt(v time.Time) *EventCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetRrule sets the "rrule" field.
func (_c *EventCreate) SetRrule(v string) *EventCreate {
	_c.mutation.SetRrule(v)
	return _c
}

// SetNillableRrule sets the "rrule" field if the given value is not nil.
func (_c *EventCreate) SetNillableRrule(v *string) *EventCreate {
	if v != nil {
		_c.SetRrule(*v)
	}
	return _c
}

// SetRruleUntil sets the "rrule_until" field.
func (_c *EventCreate) SetRruleUntil(v time.Time) *EventCreate {
	_c.mutation.SetRruleUntil(v)
	return _c
}

// SetNillableRruleUntil sets the "rrule_until" field if the given value is not nil.
func (_c *EventCreate) SetNillableRruleUntil(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetRruleUntil(*v)
	}
	return _c
}

// SetRruleCount sets the "rrule_count" field.
func (_c *EventCreate) SetRruleCount(v int) *EventCreate {
	_c.mutation.SetRruleCount(v)
	return _c
}

// SetNillableRruleCount sets the "rrule_count" field if the given value is not nil.
func (_c *EventCreate) SetNillableRruleCount(v *int) *EventCreate {
	if v != nil {
		_c.SetRruleCount(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *EventCreate) SetType(v types.EventType) *EventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_c *EventCreate) SetCoverImageURL(v string) *EventCreate {
	_c.mutation.SetCoverImageURL(v)
	return _c
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_c *EventCreate) SetNillableCoverImageURL(v *string) *EventCreate {
	if v != nil {
		_c.SetCoverImageURL(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v string) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventCreate) SetNillableID(v *string) *EventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlace sets the "place" edge to the Place entity.
func (_c *EventCreate) SetPlace(v *Place) *EventCreate {
	return _c.SetPlaceID(v.ID)
}

// AddOverrideIDs adds the "overrides" edge to the EventOverride entity by IDs.
func (_c *EventCreate) AddOverrideIDs(ids ...string) *EventCreate {
	_c.mutation.AddOverrideIDs(ids...)
	return _c
}

// AddOverrides adds the "overrides" edges to the EventOverride entity.
func (_c *EventCreate) AddOverrides(v ...*EventOverride) *EventCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOverrideIDs(ids...)
}

// AddExceptionIDs adds the "exceptions" edge to the EventException entity by IDs.
func (_c *EventCreate) AddExceptionIDs(ids ...string) *EventCreate {
	_c.mutation.AddExceptionIDs(ids...)
	return _c
}

// AddExceptions adds the "exceptions" edges to the EventException entity.
func (_c *EventCreate) AddExceptions(v ...*EventException) *EventCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExceptionIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := event.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := event.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := event.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := event.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := event.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Event.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Event.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Event.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Event.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartAt(); !ok {
		return &ValidationError{Name: "start_at", err: errors.New(`ent: missing required field "Event.start_at"`)}
	}
	if _, ok := _c.mutation.EndAt(); !ok {
		return &ValidationError{Name: "end_at", err: errors.New(`ent: missing required field "Event.end_at"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Event.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Event.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(event.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(event.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(event.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(event.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(event.FieldStartAt, field.TypeTime, value)
		_node.StartAt = value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(event.FieldEndAt, field.TypeTime, value)
		_node.EndAt = value
	}
	if value, ok := _c.mutation.Rrule(); ok {
		_spec.SetField(event.FieldRrule, field.TypeString, value)
		_node.Rrule = &value
	}
	if value, ok := _c.mutation.RruleUntil(); ok {
		_spec.SetField(event.FieldRruleUntil, field.TypeTime, value)
		_node.RruleUntil = &value
	}
	if value, ok := _c.mutation.RruleCount(); ok {
		_spec.SetField(event.FieldRruleCount, field.TypeInt, value)
		_node.RruleCount = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.CoverImageURL(); ok {
		_spec.SetField(event.FieldCoverImageURL, field.TypeString, value)
		_node.CoverImageURL = value
	}
	if nodes := _c.mutation.PlaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.PlaceTable,
			Columns: []string{event.PlaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(place.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlaceID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OverridesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OverridesTable,
			Columns: []string{event.OverridesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoverride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExceptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.ExceptionsTable,
			Columns: []string{event.ExceptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventexception.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
