// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/nashikdarshan/ent/event"
	"github.com/omkar273/nashikdarshan/ent/place"
	"github.com/omkar273/nashikdarshan/internal/types"
)

// Event is the model entity for the Event schema.
type Event struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// FK to place; NULL = city-level event
	PlaceID *string `json:"place_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Subtitle holds the value of the "subtitle" field.
	Subtitle string `json:"subtitle,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// First occurrence start
	StartAt time.Time `json:"start_at,omitempty"`
	// First occurrence end; duration reused for expanded occurrences
	EndAt time.Time `json:"end_at,omitempty"`
	// Rrule holds the value of the "rrule" field.
	Rrule *string `json:"rrule,omitempty"`
	// RruleUntil holds the value of the "rrule_until" field.
	RruleUntil *time.Time `json:"rrule_until,omitempty"`
	// RruleCount holds the value of the "rrule_count" field.
	RruleCount *int `json:"rrule_count,omitempty"`
	// aarti, festival, cultural, city_event, other
	Type types.EventType `json:"type,omitempty"`
	// CoverImageURL holds the value of the "cover_image_url" field.
	CoverImageURL string `json:"cover_image_url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventQuery when eager-loading is set.
	Edges        EventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventEdges holds the relations/edges for other nodes in the graph.
type EventEdges struct {
	// Place holds the value of the place edge.
	Place *Place `json:"place,omitempty"`
	// Overrides holds the value of the overrides edge.
	Overrides []*EventOverride `json:"overrides,omitempty"`
	// Exceptions holds the value of the exceptions edge.
	Exceptions []*EventException `json:"exceptions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PlaceOrErr returns the Place value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) PlaceOrErr() (*Place, error) {
	if e.Place != nil {
		return e.Place, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: place.Label}
	}
	return nil, &NotLoadedError{edge: "place"}
}

// OverridesOrErr returns the Overrides value or an error if the edge
// was not loaded in eager-loading.
func (e EventEdges) OverridesOrErr() ([]*EventOverride, error) {
	if e.loadedTypes[1] {
		return e.Overrides, nil
	}
	return nil, &NotLoadedError{edge: "overrides"}
}

// ExceptionsOrErr returns the Exceptions value or an error if the edge
// was not loaded in eager-loading.
func (e EventEdges) ExceptionsOrErr() ([]*EventException, error) {
	if e.loadedTypes[2] {
		return e.Exceptions, nil
	}
	return nil, &NotLoadedError{edge: "exceptions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Event) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case event.FieldMetadata:
			values[i] = new([]byte)
		case event.FieldRruleCount:
			values[i] = new(sql.NullInt64)
		case event.FieldID, event.FieldStatus, event.FieldCreatedBy, event.FieldUpdatedBy, event.FieldPlaceID, event.FieldTitle, event.FieldSubtitle, event.FieldDescription, event.FieldRrule, event.FieldType, event.FieldCoverImageURL:
			values[i] = new(sql.NullString)
		case event.FieldCreatedAt, event.FieldUpdatedAt, event.FieldStartAt, event.FieldEndAt, event.FieldRruleUntil:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Event fields.
func (_m *Event) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case event.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case event.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case event.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case event.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case event.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case event.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case event.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case event.FieldPlaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place_id", values[i])
			} else if value.Valid {
				_m.PlaceID = new(string)
				*_m.PlaceID = value.String
			}
		case event.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case event.FieldSubtitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subtitle", values[i])
			} else if value.Valid {
				_m.Subtitle = value.String
			}
		case event.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case event.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				_m.StartAt = value.Time
			}
		case event.FieldEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_at", values[i])
			} else if value.Valid {
				_m.EndAt = value.Time
			}
		case event.FieldRrule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rrule", values[i])
			} else if value.Valid {
				_m.Rrule = new(string)
				*_m.Rrule = value.String
			}
		case event.FieldRruleUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rrule_until", values[i])
			} else if value.Valid {
				_m.RruleUntil = new(time.Time)
				*_m.RruleUntil = value.Time
			}
		case event.FieldRruleCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rrule_count", values[i])
			} else if value.Valid {
				_m.RruleCount = new(int)
				*_m.RruleCount = int(value.Int64)
			}
		case event.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = types.EventType(value.String)
			}
		case event.FieldCoverImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_image_url", values[i])
			} else if value.Valid {
				_m.CoverImageURL = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Event.
// This includes values selected through modifiers, order, etc.
func (_m *Event) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlace queries the "place" edge of the Event entity.
func (_m *Event) QueryPlace() *PlaceQuery {
	return NewEventClient(_m.config).QueryPlace(_m)
}

// QueryOverrides queries the "overrides" edge of the Event entity.
func (_m *Event) QueryOverrides() *EventOverrideQuery {
	return NewEventClient(_m.config).QueryOverrides(_m)
}

// QueryExceptions queries the "exceptions" edge of the Event entity.
func (_m *Event) QueryExceptions() *EventExceptionQuery {
	return NewEventClient(_m.config).QueryExceptions(_m)
}

// Update returns a builder for updating this Event.
// Note that you need to call Event.Unwrap() before calling this method if this Event
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Event) Update() *EventUpdateOne {
	return NewEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Event entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Event) Unwrap() *Event {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Event is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Event) String() string {
	var builder strings.Builder
	builder.WriteString("Event(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.PlaceID; v != nil {
		builder.WriteString("place_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("subtitle=")
	builder.WriteString(_m.Subtitle)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("start_at=")
	builder.WriteString(_m.StartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_at=")
	builder.WriteString(_m.EndAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Rrule; v != nil {
		builder.WriteString("rrule=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RruleUntil; v != nil {
		builder.WriteString("rrule_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RruleCount; v != nil {
		builder.WriteString("rrule_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("cover_image_url=")
	builder.WriteString(_m.CoverImageURL)
	builder.WriteByte(')')
	return builder.String()
}

// Events is a parsable slice of Event.
type Events []*Event
