// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/nashikdarshan/ent/event"
	"github.com/omkar273/nashikdarshan/ent/eventoccurrence"
	"github.com/omkar273/nashikdarshan/ent/predicate"
)

// EventOccurrenceUpdate is the builder for updating EventOccurrence entities.
type EventOccurrenceUpdate struct {
	config
	hooks    []Hook
	mutation *EventOccurrenceMutation
}

// Where appends a list predicates to the EventOccurrenceUpdate builder.
func (_u *EventOccurrenceUpdate) Where(ps ...predicate.EventOccurrence) *EventOccurrenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventOccurrenceUpdate) SetStatus(v string) *EventOccurrenceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableStatus(v *string) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventOccurrenceUpdate) SetUpdatedAt(v time.Time) *EventOccurrenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EventOccurrenceUpdate) SetUpdatedBy(v string) *EventOccurrenceUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableUpdatedBy(v *string) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *EventOccurrenceUpdate) ClearUpdatedBy() *EventOccurrenceUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EventOccurrenceUpdate) SetMetadata(v map[string]string) *EventOccurrenceUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *EventOccurrenceUpdate) ClearMetadata() *EventOccurrenceUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *EventOccurrenceUpdate) SetEventID(v string) *EventOccurrenceUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableEventID(v *string) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetRecurrenceType sets the "recurrence_type" field.
func (_u *EventOccurrenceUpdate) SetRecurrenceType(v string) *EventOccurrenceUpdate {
	_u.mutation.SetRecurrenceType(v)
	return _u
}

// SetNillableRecurrenceType sets the "recurrence_type" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableRecurrenceType(v *string) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetRecurrenceType(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *EventOccurrenceUpdate) SetStartTime(v time.Time) *EventOccurrenceUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableStartTime(v *time.Time) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *EventOccurrenceUpdate) ClearStartTime() *EventOccurrenceUpdate {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *EventOccurrenceUpdate) SetEndTime(v time.Time) *EventOccurrenceUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableEndTime(v *time.Time) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *EventOccurrenceUpdate) ClearEndTime() *EventOccurrenceUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *EventOccurrenceUpdate) SetDurationMinutes(v int) *EventOccurrenceUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableDurationMinutes(v *int) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *EventOccurrenceUpdate) AddDurationMinutes(v int) *EventOccurrenceUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// ClearDurationMinutes clears the value of the "duration_minutes" field.
func (_u *EventOccurrenceUpdate) ClearDurationMinutes() *EventOccurrenceUpdate {
	_u.mutation.ClearDurationMinutes()
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *EventOccurrenceUpdate) SetDayOfWeek(v int) *EventOccurrenceUpdate {
	_u.mutation.ResetDayOfWeek()
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableDayOfWeek(v *int) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// AddDayOfWeek adds value to the "day_of_week" field.
func (_u *EventOccurrenceUpdate) AddDayOfWeek(v int) *EventOccurrenceUpdate {
	_u.mutation.AddDayOfWeek(v)
	return _u
}

// ClearDayOfWeek clears the value of the "day_of_week" field.
func (_u *EventOccurrenceUpdate) ClearDayOfWeek() *EventOccurrenceUpdate {
	_u.mutation.ClearDayOfWeek()
	return _u
}

// SetDayOfMonth sets the "day_of_month" field.
func (_u *EventOccurrenceUpdate) SetDayOfMonth(v int) *EventOccurrenceUpdate {
	_u.mutation.ResetDayOfMonth()
	_u.mutation.SetDayOfMonth(v)
	return _u
}

// SetNillableDayOfMonth sets the "day_of_month" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableDayOfMonth(v *int) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetDayOfMonth(*v)
	}
	return _u
}

// AddDayOfMonth adds value to the "day_of_month" field.
func (_u *EventOccurrenceUpdate) AddDayOfMonth(v int) *EventOccurrenceUpdate {
	_u.mutation.AddDayOfMonth(v)
	return _u
}

// ClearDayOfMonth clears the value of the "day_of_month" field.
func (_u *EventOccurrenceUpdate) ClearDayOfMonth() *EventOccurrenceUpdate {
	_u.mutation.ClearDayOfMonth()
	return _u
}

// SetMonthOfYear sets the "month_of_year" field.
func (_u *EventOccurrenceUpdate) SetMonthOfYear(v int) *EventOccurrenceUpdate {
	_u.mutation.ResetMonthOfYear()
	_u.mutation.SetMonthOfYear(v)
	return _u
}

// SetNillableMonthOfYear sets the "month_of_year" field if the given value is not nil.
func (_u *EventOccurrenceUpdate) SetNillableMonthOfYear(v *int) *EventOccurrenceUpdate {
	if v != nil {
		_u.SetMonthOfYear(*v)
	}
	return _u
}

// AddMonthOfYear adds value to the "month_of_year" field.
func (_u *EventOccurrenceUpdate) AddMonthOfYear(v int) *EventOccurrenceUpdate {
	_u.mutation.AddMonthOfYear(v)
	return _u
}

// ClearMonthOfYear clears the value of the "month_of_year" field.
func (_u *EventOccurrenceUpdate) ClearMonthOfYear() *EventOccurrenceUpdate {
	_u.mutation.ClearMonthOfYear()
	return _u
}

// SetExceptionDates sets the "exception_dates" field.
func (_u *EventOccurrenceUpdate) SetExceptionDates(v []string) *EventOccurrenceUpdate {
	_u.mutation.SetExceptionDates(v)
	return _u
}

// AppendExceptionDates appends value to the "exception_dates" field.
func (_u *EventOccurrenceUpdate) AppendExceptionDates(v []string) *EventOccurrenceUpdate {
	_u.mutation.AppendExceptionDates(v)
	return _u
}

// ClearExceptionDates clears the value of the "exception_dates" field.
func (_u *EventOccurrenceUpdate) ClearExceptionDates() *EventOccurrenceUpdate {
	_u.mutation.ClearExceptionDates()
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *EventOccurrenceUpdate) SetEvent(v *Event) *EventOccurrenceUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the EventOccurrenceMutation object of the builder.
func (_u *EventOccurrenceUpdate) Mutation() *EventOccurrenceMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *EventOccurrenceUpdate) ClearEvent() *EventOccurrenceUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventOccurrenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventOccurrenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventOccurrenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventOccurrenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventOccurrenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := eventoccurrence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventOccurrenceUpdate) check() error {
	if v, ok := _u.mutation.EventID(); ok {
		if err := eventoccurrence.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecurrenceType(); ok {
		if err := eventoccurrence.RecurrenceTypeValidator(v); err != nil {
			return &ValidationError{Name: "recurrence_type", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.recurrence_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DayOfWeek(); ok {
		if err := eventoccurrence.DayOfWeekValidator(v); err != nil {
			return &ValidationError{Name: "day_of_week", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.day_of_week": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DayOfMonth(); ok {
		if err := eventoccurrence.DayOfMonthValidator(v); err != nil {
			return &ValidationError{Name: "day_of_month", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.day_of_month": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MonthOfYear(); ok {
		if err := eventoccurrence.MonthOfYearValidator(v); err != nil {
			return &ValidationError{Name: "month_of_year", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.month_of_year": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventOccurrence.event"`)
	}
	return nil
}

func (_u *EventOccurrenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventoccurrence.Table, eventoccurrence.Columns, sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(eventoccurrence.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventoccurrence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(eventoccurrence.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(eventoccurrence.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(eventoccurrence.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(eventoccurrence.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(eventoccurrence.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.RecurrenceType(); ok {
		_spec.SetField(eventoccurrence.FieldRecurrenceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(eventoccurrence.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(eventoccurrence.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(eventoccurrence.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(eventoccurrence.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(eventoccurrence.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(eventoccurrence.FieldDurationMinutes, field.TypeInt, value)
	}
	if _u.mutation.DurationMinutesCleared() {
		_spec.ClearField(eventoccurrence.FieldDurationMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(eventoccurrence.FieldDayOfWeek, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfWeek(); ok {
		_spec.AddField(eventoccurrence.FieldDayOfWeek, field.TypeInt, value)
	}
	if _u.mutation.DayOfWeekCleared() {
		_spec.ClearField(eventoccurrence.FieldDayOfWeek, field.TypeInt)
	}
	if value, ok := _u.mutation.DayOfMonth(); ok {
		_spec.SetField(eventoccurrence.FieldDayOfMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfMonth(); ok {
		_spec.AddField(eventoccurrence.FieldDayOfMonth, field.TypeInt, value)
	}
	if _u.mutation.DayOfMonthCleared() {
		_spec.ClearField(eventoccurrence.FieldDayOfMonth, field.TypeInt)
	}
	if value, ok := _u.mutation.MonthOfYear(); ok {
		_spec.SetField(eventoccurrence.FieldMonthOfYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthOfYear(); ok {
		_spec.AddField(eventoccurrence.FieldMonthOfYear, field.TypeInt, value)
	}
	if _u.mutation.MonthOfYearCleared() {
		_spec.ClearField(eventoccurrence.FieldMonthOfYear, field.TypeInt)
	}
	if value, ok := _u.mutation.ExceptionDates(); ok {
		_spec.SetField(eventoccurrence.FieldExceptionDates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExceptionDates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, eventoccurrence.FieldExceptionDates, value)
		})
	}
	if _u.mutation.ExceptionDatesCleared() {
		_spec.ClearField(eventoccurrence.FieldExceptionDates, field.TypeJSON)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventoccurrence.EventTable,
			Columns: []string{eventoccurrence.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventoccurrence.EventTable,
			Columns: []string{eventoccurrence.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventoccurrence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventOccurrenceUpdateOne is the builder for updating a single EventOccurrence entity.
type EventOccurrenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventOccurrenceMutation
}

// SetStatus sets the "status" field.
func (_u *EventOccurrenceUpdateOne) SetStatus(v string) *EventOccurrenceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableStatus(v *string) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventOccurrenceUpdateOne) SetUpdatedAt(v time.Time) *EventOccurrenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EventOccurrenceUpdateOne) SetUpdatedBy(v string) *EventOccurrenceUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableUpdatedBy(v *string) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *EventOccurrenceUpdateOne) ClearUpdatedBy() *EventOccurrenceUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *EventOccurrenceUpdateOne) SetMetadata(v map[string]string) *EventOccurrenceUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *EventOccurrenceUpdateOne) ClearMetadata() *EventOccurrenceUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *EventOccurrenceUpdateOne) SetEventID(v string) *EventOccurrenceUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableEventID(v *string) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetRecurrenceType sets the "recurrence_type" field.
func (_u *EventOccurrenceUpdateOne) SetRecurrenceType(v string) *EventOccurrenceUpdateOne {
	_u.mutation.SetRecurrenceType(v)
	return _u
}

// SetNillableRecurrenceType sets the "recurrence_type" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableRecurrenceType(v *string) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetRecurrenceType(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *EventOccurrenceUpdateOne) SetStartTime(v time.Time) *EventOccurrenceUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableStartTime(v *time.Time) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *EventOccurrenceUpdateOne) ClearStartTime() *EventOccurrenceUpdateOne {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *EventOccurrenceUpdateOne) SetEndTime(v time.Time) *EventOccurrenceUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableEndTime(v *time.Time) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *EventOccurrenceUpdateOne) ClearEndTime() *EventOccurrenceUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *EventOccurrenceUpdateOne) SetDurationMinutes(v int) *EventOccurrenceUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableDurationMinutes(v *int) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *EventOccurrenceUpdateOne) AddDurationMinutes(v int) *EventOccurrenceUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// ClearDurationMinutes clears the value of the "duration_minutes" field.
func (_u *EventOccurrenceUpdateOne) ClearDurationMinutes() *EventOccurrenceUpdateOne {
	_u.mutation.ClearDurationMinutes()
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *EventOccurrenceUpdateOne) SetDayOfWeek(v int) *EventOccurrenceUpdateOne {
	_u.mutation.ResetDayOfWeek()
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableDayOfWeek(v *int) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// AddDayOfWeek adds value to the "day_of_week" field.
func (_u *EventOccurrenceUpdateOne) AddDayOfWeek(v int) *EventOccurrenceUpdateOne {
	_u.mutation.AddDayOfWeek(v)
	return _u
}

// ClearDayOfWeek clears the value of the "day_of_week" field.
func (_u *EventOccurrenceUpdateOne) ClearDayOfWeek() *EventOccurrenceUpdateOne {
	_u.mutation.ClearDayOfWeek()
	return _u
}

// SetDayOfMonth sets the "day_of_month" field.
func (_u *EventOccurrenceUpdateOne) SetDayOfMonth(v int) *EventOccurrenceUpdateOne {
	_u.mutation.ResetDayOfMonth()
	_u.mutation.SetDayOfMonth(v)
	return _u
}

// SetNillableDayOfMonth sets the "day_of_month" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableDayOfMonth(v *int) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetDayOfMonth(*v)
	}
	return _u
}

// AddDayOfMonth adds value to the "day_of_month" field.
func (_u *EventOccurrenceUpdateOne) AddDayOfMonth(v int) *EventOccurrenceUpdateOne {
	_u.mutation.AddDayOfMonth(v)
	return _u
}

// ClearDayOfMonth clears the value of the "day_of_month" field.
func (_u *EventOccurrenceUpdateOne) ClearDayOfMonth() *EventOccurrenceUpdateOne {
	_u.mutation.ClearDayOfMonth()
	return _u
}

// SetMonthOfYear sets the "month_of_year" field.
func (_u *EventOccurrenceUpdateOne) SetMonthOfYear(v int) *EventOccurrenceUpdateOne {
	_u.mutation.ResetMonthOfYear()
	_u.mutation.SetMonthOfYear(v)
	return _u
}

// SetNillableMonthOfYear sets the "month_of_year" field if the given value is not nil.
func (_u *EventOccurrenceUpdateOne) SetNillableMonthOfYear(v *int) *EventOccurrenceUpdateOne {
	if v != nil {
		_u.SetMonthOfYear(*v)
	}
	return _u
}

// AddMonthOfYear adds value to the "month_of_year" field.
func (_u *EventOccurrenceUpdateOne) AddMonthOfYear(v int) *EventOccurrenceUpdateOne {
	_u.mutation.AddMonthOfYear(v)
	return _u
}

// ClearMonthOfYear clears the value of the "month_of_year" field.
func (_u *EventOccurrenceUpdateOne) ClearMonthOfYear() *EventOccurrenceUpdateOne {
	_u.mutation.ClearMonthOfYear()
	return _u
}

// SetExceptionDates sets the "exception_dates" field.
func (_u *EventOccurrenceUpdateOne) SetExceptionDates(v []string) *EventOccurrenceUpdateOne {
	_u.mutation.SetExceptionDates(v)
	return _u
}

// AppendExceptionDates appends value to the "exception_dates" field.
func (_u *EventOccurrenceUpdateOne) AppendExceptionDates(v []string) *EventOccurrenceUpdateOne {
	_u.mutation.AppendExceptionDates(v)
	return _u
}

// ClearExceptionDates clears the value of the "exception_dates" field.
func (_u *EventOccurrenceUpdateOne) ClearExceptionDates() *EventOccurrenceUpdateOne {
	_u.mutation.ClearExceptionDates()
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *EventOccurrenceUpdateOne) SetEvent(v *Event) *EventOccurrenceUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the EventOccurrenceMutation object of the builder.
func (_u *EventOccurrenceUpdateOne) Mutation() *EventOccurrenceMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *EventOccurrenceUpdateOne) ClearEvent() *EventOccurrenceUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the EventOccurrenceUpdate builder.
func (_u *EventOccurrenceUpdateOne) Where(ps ...predicate.EventOccurrence) *EventOccurrenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventOccurrenceUpdateOne) Select(field string, fields ...string) *EventOccurrenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventOccurrence entity.
func (_u *EventOccurrenceUpdateOne) Save(ctx context.Context) (*EventOccurrence, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventOccurrenceUpdateOne) SaveX(ctx context.Context) *EventOccurrence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventOccurrenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventOccurrenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventOccurrenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := eventoccurrence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventOccurrenceUpdateOne) check() error {
	if v, ok := _u.mutation.EventID(); ok {
		if err := eventoccurrence.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecurrenceType(); ok {
		if err := eventoccurrence.RecurrenceTypeValidator(v); err != nil {
			return &ValidationError{Name: "recurrence_type", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.recurrence_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DayOfWeek(); ok {
		if err := eventoccurrence.DayOfWeekValidator(v); err != nil {
			return &ValidationError{Name: "day_of_week", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.day_of_week": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DayOfMonth(); ok {
		if err := eventoccurrence.DayOfMonthValidator(v); err != nil {
			return &ValidationError{Name: "day_of_month", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.day_of_month": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MonthOfYear(); ok {
		if err := eventoccurrence.MonthOfYearValidator(v); err != nil {
			return &ValidationError{Name: "month_of_year", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.month_of_year": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventOccurrence.event"`)
	}
	return nil
}

func (_u *EventOccurrenceUpdateOne) sqlSave(ctx context.Context) (_node *EventOccurrence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventoccurrence.Table, eventoccurrence.Columns, sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventOccurrence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventoccurrence.FieldID)
		for _, f := range fields {
			if !eventoccurrence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventoccurrence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(eventoccurrence.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventoccurrence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(eventoccurrence.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(eventoccurrence.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(eventoccurrence.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(eventoccurrence.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(eventoccurrence.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.RecurrenceType(); ok {
		_spec.SetField(eventoccurrence.FieldRecurrenceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(eventoccurrence.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(eventoccurrence.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(eventoccurrence.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(eventoccurrence.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(eventoccurrence.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(eventoccurrence.FieldDurationMinutes, field.TypeInt, value)
	}
	if _u.mutation.DurationMinutesCleared() {
		_spec.ClearField(eventoccurrence.FieldDurationMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(eventoccurrence.FieldDayOfWeek, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfWeek(); ok {
		_spec.AddField(eventoccurrence.FieldDayOfWeek, field.TypeInt, value)
	}
	if _u.mutation.DayOfWeekCleared() {
		_spec.ClearField(eventoccurrence.FieldDayOfWeek, field.TypeInt)
	}
	if value, ok := _u.mutation.DayOfMonth(); ok {
		_spec.SetField(eventoccurrence.FieldDayOfMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfMonth(); ok {
		_spec.AddField(eventoccurrence.FieldDayOfMonth, field.TypeInt, value)
	}
	if _u.mutation.DayOfMonthCleared() {
		_spec.ClearField(eventoccurrence.FieldDayOfMonth, field.TypeInt)
	}
	if value, ok := _u.mutation.MonthOfYear(); ok {
		_spec.SetField(eventoccurrence.FieldMonthOfYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthOfYear(); ok {
		_spec.AddField(eventoccurrence.FieldMonthOfYear, field.TypeInt, value)
	}
	if _u.mutation.MonthOfYearCleared() {
		_spec.ClearField(eventoccurrence.FieldMonthOfYear, field.TypeInt)
	}
	if value, ok := _u.mutation.ExceptionDates(); ok {
		_spec.SetField(eventoccurrence.FieldExceptionDates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExceptionDates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, eventoccurrence.FieldExceptionDates, value)
		})
	}
	if _u.mutation.ExceptionDatesCleared() {
		_spec.ClearField(eventoccurrence.FieldExceptionDates, field.TypeJSON)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventoccurrence.EventTable,
			Columns: []string{eventoccurrence.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventoccurrence.EventTable,
			Columns: []string{eventoccurrence.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EventOccurrence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventoccurrence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
