// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/nashikdarshan/ent/event"
	"github.com/omkar273/nashikdarshan/ent/eventexception"
)

// EventExceptionCreate is the builder for creating a EventException entity.
type EventExceptionCreate struct {
	config
	mutation *EventExceptionMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *EventExceptionCreate) SetStatus(v string) *EventExceptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventExceptionCreate) SetNillableStatus(v *string) *EventExceptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventExceptionCreate) SetCreatedAt(v time.Time) *EventExceptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventExceptionCreate) SetNillableCreatedAt(v *time.Time) *EventExceptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventExceptionCreate) SetUpdatedAt(v time.Time) *EventExceptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventExceptionCreate) SetNillableUpdatedAt(v *time.Time) *EventExceptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EventExceptionCreate) SetCreatedBy(v string) *EventExceptionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *EventExceptionCreate) SetNillableCreatedBy(v *string) *EventExceptionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *EventExceptionCreate) SetUpdatedBy(v string) *EventExceptionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *EventExceptionCreate) SetNillableUpdatedBy(v *string) *EventExceptionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *EventExceptionCreate) SetEventID(v string) *EventExceptionCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetOccurrenceStartAt sets the "occurrence_start_at" field.
func (_c *EventExceptionCreate) SetOccurrenceStartAt(v time.Time) *EventExceptionCreate {
	_c.mutation.SetOccurrenceStartAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EventExceptionCreate) SetID(v string) *EventExceptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventExceptionCreate) SetNillableID(v *string) *EventExceptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *EventExceptionCreate) SetEvent(v *Event) *EventExceptionCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the EventExceptionMutation object of the builder.
func (_c *EventExceptionCreate) Mutation() *EventExceptionMutation {
	return _c.mutation
}

// Save creates the EventException in the database.
func (_c *EventExceptionCreate) Save(ctx context.Context) (*EventException, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventExceptionCreate) SaveX(ctx context.Context) *EventException {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventExceptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventExceptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventExceptionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := eventexception.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := eventexception.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := eventexception.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := eventexception.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventExceptionCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EventException.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventException.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventException.updated_at"`)}
	}
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "EventException.event_id"`)}
	}
	if v, ok := _c.mutation.EventID(); ok {
		if err := eventexception.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "EventException.event_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OccurrenceStartAt(); !ok {
		return &ValidationError{Name: "occurrence_start_at", err: errors.New(`ent: missing required field "EventException.occurrence_start_at"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "EventException.event"`)}
	}
	return nil
}

func (_c *EventExceptionCreate) sqlSave(ctx context.Context) (*EventException, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EventException.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventExceptionCreate) createSpec() (*EventException, *sqlgraph.CreateSpec) {
	var (
		_node = &EventException{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventexception.Table, sqlgraph.NewFieldSpec(eventexception.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(eventexception.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventexception.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventexception.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(eventexception.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(eventexception.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.OccurrenceStartAt(); ok {
		_spec.SetField(eventexception.FieldOccurrenceStartAt, field.TypeTime, value)
		_node.OccurrenceStartAt = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventexception.EventTable,
			Columns: []string{eventexception.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventExceptionCreateBulk is the builder for creating many EventException entities in bulk.
type EventExceptionCreateBulk struct {
	config
	err      error
	builders []*EventExceptionCreate
}

// Save creates the EventException entities in the database.
func (_c *EventExceptionCreateBulk) Save(ctx context.Context) ([]*EventException, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventException, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventExceptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventExceptionCreateBulk) SaveX(ctx context.Context) []*EventException {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventExceptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventExceptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
