// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/nashikdarshan/ent/itinerary"
	"github.com/omkar273/nashikdarshan/ent/user"
	"github.com/omkar273/nashikdarshan/ent/visit"
	"github.com/shopspring/decimal"
)

// ItineraryCreate is the builder for creating a Itinerary entity.
type ItineraryCreate struct {
	config
	mutation *ItineraryMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *ItineraryCreate) SetStatus(v string) *ItineraryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableStatus(v *string) *ItineraryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItineraryCreate) SetCreatedAt(v time.Time) *ItineraryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableCreatedAt(v *time.Time) *ItineraryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItineraryCreate) SetUpdatedAt(v time.Time) *ItineraryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableUpdatedAt(v *time.Time) *ItineraryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ItineraryCreate) SetCreatedBy(v string) *ItineraryCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableCreatedBy(v *string) *ItineraryCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ItineraryCreate) SetUpdatedBy(v string) *ItineraryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableUpdatedBy(v *string) *ItineraryCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ItineraryCreate) SetMetadata(v map[string]string) *ItineraryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ItineraryCreate) SetUserID(v string) *ItineraryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ItineraryCreate) SetTitle(v string) *ItineraryCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ItineraryCreate) SetDescription(v string) *ItineraryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableDescription(v *string) *ItineraryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPlannedDate sets the "planned_date" field.
func (_c *ItineraryCreate) SetPlannedDate(v time.Time) *ItineraryCreate {
	_c.mutation.SetPlannedDate(v)
	return _c
}

// SetNillablePlannedDate sets the "planned_date" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillablePlannedDate(v *time.Time) *ItineraryCreate {
	if v != nil {
		_c.SetPlannedDate(*v)
	}
	return _c
}

// SetStartLatitude sets the "start_latitude" field.
func (_c *ItineraryCreate) SetStartLatitude(v decimal.Decimal) *ItineraryCreate {
	_c.mutation.SetStartLatitude(v)
	return _c
}

// SetStartLongitude sets the "start_longitude" field.
func (_c *ItineraryCreate) SetStartLongitude(v decimal.Decimal) *ItineraryCreate {
	_c.mutation.SetStartLongitude(v)
	return _c
}

// SetPreferredTransportMode sets the "preferred_transport_mode" field.
func (_c *ItineraryCreate) SetPreferredTransportMode(v string) *ItineraryCreate {
	_c.mutation.SetPreferredTransportMode(v)
	return _c
}

// SetNillablePreferredTransportMode sets the "preferred_transport_mode" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillablePreferredTransportMode(v *string) *ItineraryCreate {
	if v != nil {
		_c.SetPreferredTransportMode(*v)
	}
	return _c
}

// SetTotalDistanceKm sets the "total_distance_km" field.
func (_c *ItineraryCreate) SetTotalDistanceKm(v float64) *ItineraryCreate {
	_c.mutation.SetTotalDistanceKm(v)
	return _c
}

// SetNillableTotalDistanceKm sets the "total_distance_km" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableTotalDistanceKm(v *float64) *ItineraryCreate {
	if v != nil {
		_c.SetTotalDistanceKm(*v)
	}
	return _c
}

// SetTotalDurationMinutes sets the "total_duration_minutes" field.
func (_c *ItineraryCreate) SetTotalDurationMinutes(v int) *ItineraryCreate {
	_c.mutation.SetTotalDurationMinutes(v)
	return _c
}

// SetNillableTotalDurationMinutes sets the "total_duration_minutes" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableTotalDurationMinutes(v *int) *ItineraryCreate {
	if v != nil {
		_c.SetTotalDurationMinutes(*v)
	}
	return _c
}

// SetTotalVisitTimeMinutes sets the "total_visit_time_minutes" field.
func (_c *ItineraryCreate) SetTotalVisitTimeMinutes(v int) *ItineraryCreate {
	_c.mutation.SetTotalVisitTimeMinutes(v)
	return _c
}

// SetNillableTotalVisitTimeMinutes sets the "total_visit_time_minutes" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableTotalVisitTimeMinutes(v *int) *ItineraryCreate {
	if v != nil {
		_c.SetTotalVisitTimeMinutes(*v)
	}
	return _c
}

// SetIsOptimized sets the "is_optimized" field.
func (_c *ItineraryCreate) SetIsOptimized(v bool) *ItineraryCreate {
	_c.mutation.SetIsOptimized(v)
	return _c
}

// SetNillableIsOptimized sets the "is_optimized" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableIsOptimized(v *bool) *ItineraryCreate {
	if v != nil {
		_c.SetIsOptimized(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItineraryCreate) SetID(v string) *ItineraryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ItineraryCreate) SetNillableID(v *string) *ItineraryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ItineraryCreate) SetUser(v *User) *ItineraryCreate {
	return _c.SetUserID(v.ID)
}

// AddVisitIDs adds the "visits" edge to the Visit entity by IDs.
func (_c *ItineraryCreate) AddVisitIDs(ids ...string) *ItineraryCreate {
	_c.mutation.AddVisitIDs(ids...)
	return _c
}

// AddVisits adds the "visits" edges to the Visit entity.
func (_c *ItineraryCreate) AddVisits(v ...*Visit) *ItineraryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVisitIDs(ids...)
}

// Mutation returns the ItineraryMutation object of the builder.
func (_c *ItineraryCreate) Mutation() *ItineraryMutation {
	return _c.mutation
}

// Save creates the Itinerary in the database.
func (_c *ItineraryCreate) Save(ctx context.Context) (*Itinerary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItineraryCreate) SaveX(ctx context.Context) *Itinerary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItineraryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItineraryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItineraryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := itinerary.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := itinerary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := itinerary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := itinerary.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.PlannedDate(); !ok {
		v := itinerary.DefaultPlannedDate()
		_c.mutation.SetPlannedDate(v)
	}
	if _, ok := _c.mutation.PreferredTransportMode(); !ok {
		v := itinerary.DefaultPreferredTransportMode
		_c.mutation.SetPreferredTransportMode(v)
	}
	if _, ok := _c.mutation.IsOptimized(); !ok {
		v := itinerary.DefaultIsOptimized
		_c.mutation.SetIsOptimized(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := itinerary.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItineraryCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Itinerary.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Itinerary.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Itinerary.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Itinerary.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := itinerary.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Itinerary.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Itinerary.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := itinerary.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Itinerary.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlannedDate(); !ok {
		return &ValidationError{Name: "planned_date", err: errors.New(`ent: missing required field "Itinerary.planned_date"`)}
	}
	if _, ok := _c.mutation.StartLatitude(); !ok {
		return &ValidationError{Name: "start_latitude", err: errors.New(`ent: missing required field "Itinerary.start_latitude"`)}
	}
	if _, ok := _c.mutation.StartLongitude(); !ok {
		return &ValidationError{Name: "start_longitude", err: errors.New(`ent: missing required field "Itinerary.start_longitude"`)}
	}
	if _, ok := _c.mutation.PreferredTransportMode(); !ok {
		return &ValidationError{Name: "preferred_transport_mode", err: errors.New(`ent: missing required field "Itinerary.preferred_transport_mode"`)}
	}
	if _, ok := _c.mutation.IsOptimized(); !ok {
		return &ValidationError{Name: "is_optimized", err: errors.New(`ent: missing required field "Itinerary.is_optimized"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := itinerary.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Itinerary.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Itinerary.user"`)}
	}
	return nil
}

func (_c *ItineraryCreate) sqlSave(ctx context.Context) (*Itinerary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Itinerary.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItineraryCreate) createSpec() (*Itinerary, *sqlgraph.CreateSpec) {
	var (
		_node = &Itinerary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itinerary.Table, sqlgraph.NewFieldSpec(itinerary.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(itinerary.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(itinerary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(itinerary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(itinerary.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(itinerary.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(itinerary.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(itinerary.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(itinerary.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.PlannedDate(); ok {
		_spec.SetField(itinerary.FieldPlannedDate, field.TypeTime, value)
		_node.PlannedDate = value
	}
	if value, ok := _c.mutation.StartLatitude(); ok {
		_spec.SetField(itinerary.FieldStartLatitude, field.TypeOther, value)
		_node.StartLatitude = value
	}
	if value, ok := _c.mutation.StartLongitude(); ok {
		_spec.SetField(itinerary.FieldStartLongitude, field.TypeOther, value)
		_node.StartLongitude = value
	}
	if value, ok := _c.mutation.PreferredTransportMode(); ok {
		_spec.SetField(itinerary.FieldPreferredTransportMode, field.TypeString, value)
		_node.PreferredTransportMode = value
	}
	if value, ok := _c.mutation.TotalDistanceKm(); ok {
		_spec.SetField(itinerary.FieldTotalDistanceKm, field.TypeFloat64, value)
		_node.TotalDistanceKm = &value
	}
	if value, ok := _c.mutation.TotalDurationMinutes(); ok {
		_spec.SetField(itinerary.FieldTotalDurationMinutes, field.TypeInt, value)
		_node.TotalDurationMinutes = &value
	}
	if value, ok := _c.mutation.TotalVisitTimeMinutes(); ok {
		_spec.SetField(itinerary.FieldTotalVisitTimeMinutes, field.TypeInt, value)
		_node.TotalVisitTimeMinutes = &value
	}
	if value, ok := _c.mutation.IsOptimized(); ok {
		_spec.SetField(itinerary.FieldIsOptimized, field.TypeBool, value)
		_node.IsOptimized = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itinerary.UserTable,
			Columns: []string{itinerary.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VisitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itinerary.VisitsTable,
			Columns: []string{itinerary.VisitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ItineraryCreateBulk is the builder for creating many Itinerary entities in bulk.
type ItineraryCreateBulk struct {
	config
	err      error
	builders []*ItineraryCreate
}

// Save creates the Itinerary entities in the database.
func (_c *ItineraryCreateBulk) Save(ctx context.Context) ([]*Itinerary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Itinerary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItineraryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItineraryCreateBulk) SaveX(ctx context.Context) []*Itinerary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItineraryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItineraryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
