// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/nashikdarshan/ent/category"
	"github.com/omkar273/nashikdarshan/ent/place"
	"github.com/omkar273/nashikdarshan/ent/placeimage"
	"github.com/shopspring/decimal"
)

// PlaceCreate is the builder for creating a Place entity.
type PlaceCreate struct {
	config
	mutation *PlaceMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *PlaceCreate) SetStatus(v string) *PlaceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableStatus(v *string) *PlaceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlaceCreate) SetCreatedAt(v time.Time) *PlaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableCreatedAt(v *time.Time) *PlaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlaceCreate) SetUpdatedAt(v time.Time) *PlaceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableUpdatedAt(v *time.Time) *PlaceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PlaceCreate) SetCreatedBy(v string) *PlaceCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableCreatedBy(v *string) *PlaceCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PlaceCreate) SetUpdatedBy(v string) *PlaceCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableUpdatedBy(v *string) *PlaceCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *PlaceCreate) SetMetadata(v map[string]string) *PlaceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *PlaceCreate) SetSlug(v string) *PlaceCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PlaceCreate) SetTitle(v string) *PlaceCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *PlaceCreate) SetSubtitle(v string) *PlaceCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableSubtitle(v *string) *PlaceCreate {
	if v != nil {
		_c.SetSubtitle(*v)
	}
	return _c
}

// SetShortDescription sets the "short_description" field.
func (_c *PlaceCreate) SetShortDescription(v string) *PlaceCreate {
	_c.mutation.SetShortDescription(v)
	return _c
}

// SetNillableShortDescription sets the "short_description" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableShortDescription(v *string) *PlaceCreate {
	if v != nil {
		_c.SetShortDescription(*v)
	}
	return _c
}

// SetLongDescription sets the "long_description" field.
func (_c *PlaceCreate) SetLongDescription(v string) *PlaceCreate {
	_c.mutation.SetLongDescription(v)
	return _c
}

// SetNillableLongDescription sets the "long_description" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableLongDescription(v *string) *PlaceCreate {
	if v != nil {
		_c.SetLongDescription(*v)
	}
	return _c
}

// SetPlaceType sets the "place_type" field.
func (_c *PlaceCreate) SetPlaceType(v string) *PlaceCreate {
	_c.mutation.SetPlaceType(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *PlaceCreate) SetAddress(v map[string]string) *PlaceCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *PlaceCreate) SetLatitude(v decimal.Decimal) *PlaceCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableLatitude(v *decimal.Decimal) *PlaceCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *PlaceCreate) SetLongitude(v decimal.Decimal) *PlaceCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableLongitude(v *decimal.Decimal) *PlaceCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetPrimaryImageURL sets the "primary_image_url" field.
func (_c *PlaceCreate) SetPrimaryImageURL(v string) *PlaceCreate {
	_c.mutation.SetPrimaryImageURL(v)
	return _c
}

// SetNillablePrimaryImageURL sets the "primary_image_url" field if the given value is not nil.
func (_c *PlaceCreate) SetNillablePrimaryImageURL(v *string) *PlaceCreate {
	if v != nil {
		_c.SetPrimaryImageURL(*v)
	}
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *PlaceCreate) SetThumbnailURL(v string) *PlaceCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableThumbnailURL(v *string) *PlaceCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PlaceCreate) SetViewCount(v int) *PlaceCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableViewCount(v *int) *PlaceCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetRatingAvg sets the "rating_avg" field.
func (_c *PlaceCreate) SetRatingAvg(v decimal.Decimal) *PlaceCreate {
	_c.mutation.SetRatingAvg(v)
	return _c
}

// SetNillableRatingAvg sets the "rating_avg" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableRatingAvg(v *decimal.Decimal) *PlaceCreate {
	if v != nil {
		_c.SetRatingAvg(*v)
	}
	return _c
}

// SetRatingCount sets the "rating_count" field.
func (_c *PlaceCreate) SetRatingCount(v int) *PlaceCreate {
	_c.mutation.SetRatingCount(v)
	return _c
}

// SetNillableRatingCount sets the "rating_count" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableRatingCount(v *int) *PlaceCreate {
	if v != nil {
		_c.SetRatingCount(*v)
	}
	return _c
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_c *PlaceCreate) SetLastViewedAt(v time.Time) *PlaceCreate {
	_c.mutation.SetLastViewedAt(v)
	return _c
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableLastViewedAt(v *time.Time) *PlaceCreate {
	if v != nil {
		_c.SetLastViewedAt(*v)
	}
	return _c
}

// SetPopularityScore sets the "popularity_score" field.
func (_c *PlaceCreate) SetPopularityScore(v decimal.Decimal) *PlaceCreate {
	_c.mutation.SetPopularityScore(v)
	return _c
}

// SetNillablePopularityScore sets the "popularity_score" field if the given value is not nil.
func (_c *PlaceCreate) SetNillablePopularityScore(v *decimal.Decimal) *PlaceCreate {
	if v != nil {
		_c.SetPopularityScore(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlaceCreate) SetID(v string) *PlaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlaceCreate) SetNillableID(v *string) *PlaceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddImageIDs adds the "images" edge to the PlaceImage entity by IDs.
func (_c *PlaceCreate) AddImageIDs(ids ...string) *PlaceCreate {
	_c.mutation.AddImageIDs(ids...)
	return _c
}

// AddImages adds the "images" edges to the PlaceImage entity.
func (_c *PlaceCreate) AddImages(v ...*PlaceImage) *PlaceCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddImageIDs(ids...)
}

// AddCategoryIDs adds the "category" edge to the Category entity by IDs.
func (_c *PlaceCreate) AddCategoryIDs(ids ...string) *PlaceCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategory adds the "category" edges to the Category entity.
func (_c *PlaceCreate) AddCategory(v ...*Category) *PlaceCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// Mutation returns the PlaceMutation object of the builder.
func (_c *PlaceCreate) Mutation() *PlaceMutation {
	return _c.mutation
}

// Save creates the Place in the database.
func (_c *PlaceCreate) Save(ctx context.Context) (*Place, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaceCreate) SaveX(ctx context.Context) *Place {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaceCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := place.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := place.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := place.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := place.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		v := place.DefaultLatitude
		_c.mutation.SetLatitude(v)
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		v := place.DefaultLongitude
		_c.mutation.SetLongitude(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := place.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.RatingAvg(); !ok {
		v := place.DefaultRatingAvg
		_c.mutation.SetRatingAvg(v)
	}
	if _, ok := _c.mutation.RatingCount(); !ok {
		v := place.DefaultRatingCount
		_c.mutation.SetRatingCount(v)
	}
	if _, ok := _c.mutation.PopularityScore(); !ok {
		v := place.DefaultPopularityScore
		_c.mutation.SetPopularityScore(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := place.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaceCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Place.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Place.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Place.updated_at"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Place.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := place.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Place.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Place.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := place.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Place.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlaceType(); !ok {
		return &ValidationError{Name: "place_type", err: errors.New(`ent: missing required field "Place.place_type"`)}
	}
	if v, ok := _c.mutation.PlaceType(); ok {
		if err := place.PlaceTypeValidator(v); err != nil {
			return &ValidationError{Name: "place_type", err: fmt.Errorf(`ent: validator failed for field "Place.place_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "Place.latitude"`)}
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		return &ValidationError{Name: "longitude", err: errors.New(`ent: missing required field "Place.longitude"`)}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Place.view_count"`)}
	}
	if v, ok := _c.mutation.ViewCount(); ok {
		if err := place.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Place.view_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RatingAvg(); !ok {
		return &ValidationError{Name: "rating_avg", err: errors.New(`ent: missing required field "Place.rating_avg"`)}
	}
	if _, ok := _c.mutation.RatingCount(); !ok {
		return &ValidationError{Name: "rating_count", err: errors.New(`ent: missing required field "Place.rating_count"`)}
	}
	if v, ok := _c.mutation.RatingCount(); ok {
		if err := place.RatingCountValidator(v); err != nil {
			return &ValidationError{Name: "rating_count", err: fmt.Errorf(`ent: validator failed for field "Place.rating_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PopularityScore(); !ok {
		return &ValidationError{Name: "popularity_score", err: errors.New(`ent: missing required field "Place.popularity_score"`)}
	}
	return nil
}

func (_c *PlaceCreate) sqlSave(ctx context.Context) (*Place, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Place.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaceCreate) createSpec() (*Place, *sqlgraph.CreateSpec) {
	var (
		_node = &Place{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(place.Table, sqlgraph.NewFieldSpec(place.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(place.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(place.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(place.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(place.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(place.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(place.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(place.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(place.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(place.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.ShortDescription(); ok {
		_spec.SetField(place.FieldShortDescription, field.TypeString, value)
		_node.ShortDescription = value
	}
	if value, ok := _c.mutation.LongDescription(); ok {
		_spec.SetField(place.FieldLongDescription, field.TypeString, value)
		_node.LongDescription = value
	}
	if value, ok := _c.mutation.PlaceType(); ok {
		_spec.SetField(place.FieldPlaceType, field.TypeString, value)
		_node.PlaceType = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(place.FieldAddress, field.TypeJSON, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(place.FieldLatitude, field.TypeOther, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(place.FieldLongitude, field.TypeOther, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.PrimaryImageURL(); ok {
		_spec.SetField(place.FieldPrimaryImageURL, field.TypeString, value)
		_node.PrimaryImageURL = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(place.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(place.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.RatingAvg(); ok {
		_spec.SetField(place.FieldRatingAvg, field.TypeOther, value)
		_node.RatingAvg = value
	}
	if value, ok := _c.mutation.RatingCount(); ok {
		_spec.SetField(place.FieldRatingCount, field.TypeInt, value)
		_node.RatingCount = value
	}
	if value, ok := _c.mutation.LastViewedAt(); ok {
		_spec.SetField(place.FieldLastViewedAt, field.TypeTime, value)
		_node.LastViewedAt = value
	}
	if value, ok := _c.mutation.PopularityScore(); ok {
		_spec.SetField(place.FieldPopularityScore, field.TypeOther, value)
		_node.PopularityScore = value
	}
	if nodes := _c.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   place.ImagesTable,
			Columns: []string{place.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(placeimage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   place.CategoryTable,
			Columns: place.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlaceCreateBulk is the builder for creating many Place entities in bulk.
type PlaceCreateBulk struct {
	config
	err      error
	builders []*PlaceCreate
}

// Save creates the Place entities in the database.
func (_c *PlaceCreateBulk) Save(ctx context.Context) ([]*Place, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Place, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaceCreateBulk) SaveX(ctx context.Context) []*Place {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
