// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/nashikdarshan/ent/place"
	"github.com/omkar273/nashikdarshan/ent/placeimage"
)

// PlaceImage is the model entity for the PlaceImage schema.
type PlaceImage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// PlaceID holds the value of the "place_id" field.
	PlaceID string `json:"place_id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Alt holds the value of the "alt" field.
	Alt string `json:"alt,omitempty"`
	// Pos holds the value of the "pos" field.
	Pos int `json:"pos,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlaceImageQuery when eager-loading is set.
	Edges        PlaceImageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlaceImageEdges holds the relations/edges for other nodes in the graph.
type PlaceImageEdges struct {
	// Place holds the value of the place edge.
	Place *Place `json:"place,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlaceOrErr returns the Place value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlaceImageEdges) PlaceOrErr() (*Place, error) {
	if e.Place != nil {
		return e.Place, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: place.Label}
	}
	return nil, &NotLoadedError{edge: "place"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlaceImage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case placeimage.FieldMetadata:
			values[i] = new([]byte)
		case placeimage.FieldPos:
			values[i] = new(sql.NullInt64)
		case placeimage.FieldID, placeimage.FieldStatus, placeimage.FieldCreatedBy, placeimage.FieldUpdatedBy, placeimage.FieldPlaceID, placeimage.FieldURL, placeimage.FieldAlt:
			values[i] = new(sql.NullString)
		case placeimage.FieldCreatedAt, placeimage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlaceImage fields.
func (_m *PlaceImage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case placeimage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case placeimage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case placeimage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case placeimage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case placeimage.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case placeimage.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case placeimage.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case placeimage.FieldPlaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place_id", values[i])
			} else if value.Valid {
				_m.PlaceID = value.String
			}
		case placeimage.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case placeimage.FieldAlt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alt", values[i])
			} else if value.Valid {
				_m.Alt = value.String
			}
		case placeimage.FieldPos:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pos", values[i])
			} else if value.Valid {
				_m.Pos = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlaceImage.
// This includes values selected through modifiers, order, etc.
func (_m *PlaceImage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlace queries the "place" edge of the PlaceImage entity.
func (_m *PlaceImage) QueryPlace() *PlaceQuery {
	return NewPlaceImageClient(_m.config).QueryPlace(_m)
}

// Update returns a builder for updating this PlaceImage.
// Note that you need to call PlaceImage.Unwrap() before calling this method if this PlaceImage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlaceImage) Update() *PlaceImageUpdateOne {
	return NewPlaceImageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlaceImage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlaceImage) Unwrap() *PlaceImage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlaceImage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlaceImage) String() string {
	var builder strings.Builder
	builder.WriteString("PlaceImage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("place_id=")
	builder.WriteString(_m.PlaceID)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("alt=")
	builder.WriteString(_m.Alt)
	builder.WriteString(", ")
	builder.WriteString("pos=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pos))
	builder.WriteByte(')')
	return builder.String()
}

// PlaceImages is a parsable slice of PlaceImage.
type PlaceImages []*PlaceImage
