// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/omkar273/nashikdarshan/ent/category"
	"github.com/omkar273/nashikdarshan/ent/place"
	"github.com/omkar273/nashikdarshan/ent/placeimage"
	"github.com/omkar273/nashikdarshan/ent/review"
	"github.com/omkar273/nashikdarshan/ent/schema"
	"github.com/omkar273/nashikdarshan/ent/secret"
	"github.com/omkar273/nashikdarshan/ent/user"
	"github.com/omkar273/nashikdarshan/internal/types"
	"github.com/shopspring/decimal"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryMixinFields1 := categoryMixin[1].Fields()
	_ = categoryMixinFields1
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescStatus is the schema descriptor for status field.
	categoryDescStatus := categoryMixinFields0[0].Descriptor()
	// category.DefaultStatus holds the default value on creation for the status field.
	category.DefaultStatus = categoryDescStatus.Default.(string)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[2].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescMetadata is the schema descriptor for metadata field.
	categoryDescMetadata := categoryMixinFields1[0].Descriptor()
	// category.DefaultMetadata holds the default value on creation for the metadata field.
	category.DefaultMetadata = categoryDescMetadata.Default.(map[string]string)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[2].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.IDValidator is a validator for the "id" field. It is called by the builders before save.
	category.IDValidator = categoryDescID.Validators[0].(func(string) error)
	placeMixin := schema.Place{}.Mixin()
	placeMixinFields0 := placeMixin[0].Fields()
	_ = placeMixinFields0
	placeMixinFields1 := placeMixin[1].Fields()
	_ = placeMixinFields1
	placeFields := schema.Place{}.Fields()
	_ = placeFields
	// placeDescStatus is the schema descriptor for status field.
	placeDescStatus := placeMixinFields0[0].Descriptor()
	// place.DefaultStatus holds the default value on creation for the status field.
	place.DefaultStatus = placeDescStatus.Default.(string)
	// placeDescCreatedAt is the schema descriptor for created_at field.
	placeDescCreatedAt := placeMixinFields0[1].Descriptor()
	// place.DefaultCreatedAt holds the default value on creation for the created_at field.
	place.DefaultCreatedAt = placeDescCreatedAt.Default.(func() time.Time)
	// placeDescUpdatedAt is the schema descriptor for updated_at field.
	placeDescUpdatedAt := placeMixinFields0[2].Descriptor()
	// place.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	place.DefaultUpdatedAt = placeDescUpdatedAt.Default.(func() time.Time)
	// place.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	place.UpdateDefaultUpdatedAt = placeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// placeDescMetadata is the schema descriptor for metadata field.
	placeDescMetadata := placeMixinFields1[0].Descriptor()
	// place.DefaultMetadata holds the default value on creation for the metadata field.
	place.DefaultMetadata = placeDescMetadata.Default.(map[string]string)
	// placeDescSlug is the schema descriptor for slug field.
	placeDescSlug := placeFields[1].Descriptor()
	// place.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	place.SlugValidator = placeDescSlug.Validators[0].(func(string) error)
	// placeDescTitle is the schema descriptor for title field.
	placeDescTitle := placeFields[2].Descriptor()
	// place.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	place.TitleValidator = placeDescTitle.Validators[0].(func(string) error)
	// placeDescViewCount is the schema descriptor for view_count field.
	placeDescViewCount := placeFields[10].Descriptor()
	// place.DefaultViewCount holds the default value on creation for the view_count field.
	place.DefaultViewCount = placeDescViewCount.Default.(int)
	// place.ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	place.ViewCountValidator = placeDescViewCount.Validators[0].(func(int) error)
	// placeDescRatingAvg is the schema descriptor for rating_avg field.
	placeDescRatingAvg := placeFields[11].Descriptor()
	// place.DefaultRatingAvg holds the default value on creation for the rating_avg field.
	place.DefaultRatingAvg = placeDescRatingAvg.Default.(decimal.Decimal)
	// placeDescRatingCount is the schema descriptor for rating_count field.
	placeDescRatingCount := placeFields[12].Descriptor()
	// place.DefaultRatingCount holds the default value on creation for the rating_count field.
	place.DefaultRatingCount = placeDescRatingCount.Default.(int)
	// place.RatingCountValidator is a validator for the "rating_count" field. It is called by the builders before save.
	place.RatingCountValidator = placeDescRatingCount.Validators[0].(func(int) error)
	// placeDescPopularityScore is the schema descriptor for popularity_score field.
	placeDescPopularityScore := placeFields[13].Descriptor()
	// place.DefaultPopularityScore holds the default value on creation for the popularity_score field.
	place.DefaultPopularityScore = placeDescPopularityScore.Default.(decimal.Decimal)
	// placeDescID is the schema descriptor for id field.
	placeDescID := placeFields[0].Descriptor()
	// place.DefaultID holds the default value on creation for the id field.
	place.DefaultID = placeDescID.Default.(func() string)
	placeimageMixin := schema.PlaceImage{}.Mixin()
	placeimageMixinFields0 := placeimageMixin[0].Fields()
	_ = placeimageMixinFields0
	placeimageMixinFields1 := placeimageMixin[1].Fields()
	_ = placeimageMixinFields1
	placeimageFields := schema.PlaceImage{}.Fields()
	_ = placeimageFields
	// placeimageDescStatus is the schema descriptor for status field.
	placeimageDescStatus := placeimageMixinFields0[0].Descriptor()
	// placeimage.DefaultStatus holds the default value on creation for the status field.
	placeimage.DefaultStatus = placeimageDescStatus.Default.(string)
	// placeimageDescCreatedAt is the schema descriptor for created_at field.
	placeimageDescCreatedAt := placeimageMixinFields0[1].Descriptor()
	// placeimage.DefaultCreatedAt holds the default value on creation for the created_at field.
	placeimage.DefaultCreatedAt = placeimageDescCreatedAt.Default.(func() time.Time)
	// placeimageDescUpdatedAt is the schema descriptor for updated_at field.
	placeimageDescUpdatedAt := placeimageMixinFields0[2].Descriptor()
	// placeimage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	placeimage.DefaultUpdatedAt = placeimageDescUpdatedAt.Default.(func() time.Time)
	// placeimage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	placeimage.UpdateDefaultUpdatedAt = placeimageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// placeimageDescMetadata is the schema descriptor for metadata field.
	placeimageDescMetadata := placeimageMixinFields1[0].Descriptor()
	// placeimage.DefaultMetadata holds the default value on creation for the metadata field.
	placeimage.DefaultMetadata = placeimageDescMetadata.Default.(map[string]string)
	// placeimageDescPlaceID is the schema descriptor for place_id field.
	placeimageDescPlaceID := placeimageFields[1].Descriptor()
	// placeimage.PlaceIDValidator is a validator for the "place_id" field. It is called by the builders before save.
	placeimage.PlaceIDValidator = placeimageDescPlaceID.Validators[0].(func(string) error)
	// placeimageDescURL is the schema descriptor for url field.
	placeimageDescURL := placeimageFields[2].Descriptor()
	// placeimage.URLValidator is a validator for the "url" field. It is called by the builders before save.
	placeimage.URLValidator = placeimageDescURL.Validators[0].(func(string) error)
	// placeimageDescPos is the schema descriptor for pos field.
	placeimageDescPos := placeimageFields[4].Descriptor()
	// placeimage.DefaultPos holds the default value on creation for the pos field.
	placeimage.DefaultPos = placeimageDescPos.Default.(int)
	// placeimageDescID is the schema descriptor for id field.
	placeimageDescID := placeimageFields[0].Descriptor()
	// placeimage.DefaultID holds the default value on creation for the id field.
	placeimage.DefaultID = placeimageDescID.Default.(func() string)
	reviewMixin := schema.Review{}.Mixin()
	reviewMixinFields0 := reviewMixin[0].Fields()
	_ = reviewMixinFields0
	reviewMixinFields1 := reviewMixin[1].Fields()
	_ = reviewMixinFields1
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescStatus is the schema descriptor for status field.
	reviewDescStatus := reviewMixinFields0[0].Descriptor()
	// review.DefaultStatus holds the default value on creation for the status field.
	review.DefaultStatus = reviewDescStatus.Default.(string)
	// reviewDescCreatedAt is the schema descriptor for created_at field.
	reviewDescCreatedAt := reviewMixinFields0[1].Descriptor()
	// review.DefaultCreatedAt holds the default value on creation for the created_at field.
	review.DefaultCreatedAt = reviewDescCreatedAt.Default.(func() time.Time)
	// reviewDescUpdatedAt is the schema descriptor for updated_at field.
	reviewDescUpdatedAt := reviewMixinFields0[2].Descriptor()
	// review.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	review.DefaultUpdatedAt = reviewDescUpdatedAt.Default.(func() time.Time)
	// review.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	review.UpdateDefaultUpdatedAt = reviewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// reviewDescMetadata is the schema descriptor for metadata field.
	reviewDescMetadata := reviewMixinFields1[0].Descriptor()
	// review.DefaultMetadata holds the default value on creation for the metadata field.
	review.DefaultMetadata = reviewDescMetadata.Default.(map[string]string)
	// reviewDescEntityType is the schema descriptor for entity_type field.
	reviewDescEntityType := reviewFields[1].Descriptor()
	// review.EntityTypeValidator is a validator for the "entity_type" field. It is called by the builders before save.
	review.EntityTypeValidator = reviewDescEntityType.Validators[0].(func(string) error)
	// reviewDescEntityID is the schema descriptor for entity_id field.
	reviewDescEntityID := reviewFields[2].Descriptor()
	// review.EntityIDValidator is a validator for the "entity_id" field. It is called by the builders before save.
	review.EntityIDValidator = reviewDescEntityID.Validators[0].(func(string) error)
	// reviewDescUserID is the schema descriptor for user_id field.
	reviewDescUserID := reviewFields[3].Descriptor()
	// review.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	review.UserIDValidator = reviewDescUserID.Validators[0].(func(string) error)
	// reviewDescHelpfulCount is the schema descriptor for helpful_count field.
	reviewDescHelpfulCount := reviewFields[9].Descriptor()
	// review.DefaultHelpfulCount holds the default value on creation for the helpful_count field.
	review.DefaultHelpfulCount = reviewDescHelpfulCount.Default.(int)
	// review.HelpfulCountValidator is a validator for the "helpful_count" field. It is called by the builders before save.
	review.HelpfulCountValidator = reviewDescHelpfulCount.Validators[0].(func(int) error)
	// reviewDescNotHelpfulCount is the schema descriptor for not_helpful_count field.
	reviewDescNotHelpfulCount := reviewFields[10].Descriptor()
	// review.DefaultNotHelpfulCount holds the default value on creation for the not_helpful_count field.
	review.DefaultNotHelpfulCount = reviewDescNotHelpfulCount.Default.(int)
	// review.NotHelpfulCountValidator is a validator for the "not_helpful_count" field. It is called by the builders before save.
	review.NotHelpfulCountValidator = reviewDescNotHelpfulCount.Validators[0].(func(int) error)
	// reviewDescIsVerified is the schema descriptor for is_verified field.
	reviewDescIsVerified := reviewFields[11].Descriptor()
	// review.DefaultIsVerified holds the default value on creation for the is_verified field.
	review.DefaultIsVerified = reviewDescIsVerified.Default.(bool)
	// reviewDescIsFeatured is the schema descriptor for is_featured field.
	reviewDescIsFeatured := reviewFields[12].Descriptor()
	// review.DefaultIsFeatured holds the default value on creation for the is_featured field.
	review.DefaultIsFeatured = reviewDescIsFeatured.Default.(bool)
	// reviewDescID is the schema descriptor for id field.
	reviewDescID := reviewFields[0].Descriptor()
	// review.IDValidator is a validator for the "id" field. It is called by the builders before save.
	review.IDValidator = reviewDescID.Validators[0].(func(string) error)
	secretMixin := schema.Secret{}.Mixin()
	secretMixinFields0 := secretMixin[0].Fields()
	_ = secretMixinFields0
	secretMixinFields1 := secretMixin[1].Fields()
	_ = secretMixinFields1
	secretFields := schema.Secret{}.Fields()
	_ = secretFields
	// secretDescStatus is the schema descriptor for status field.
	secretDescStatus := secretMixinFields0[0].Descriptor()
	// secret.DefaultStatus holds the default value on creation for the status field.
	secret.DefaultStatus = secretDescStatus.Default.(string)
	// secretDescCreatedAt is the schema descriptor for created_at field.
	secretDescCreatedAt := secretMixinFields0[1].Descriptor()
	// secret.DefaultCreatedAt holds the default value on creation for the created_at field.
	secret.DefaultCreatedAt = secretDescCreatedAt.Default.(func() time.Time)
	// secretDescUpdatedAt is the schema descriptor for updated_at field.
	secretDescUpdatedAt := secretMixinFields0[2].Descriptor()
	// secret.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	secret.DefaultUpdatedAt = secretDescUpdatedAt.Default.(func() time.Time)
	// secret.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	secret.UpdateDefaultUpdatedAt = secretDescUpdatedAt.UpdateDefault.(func() time.Time)
	// secretDescMetadata is the schema descriptor for metadata field.
	secretDescMetadata := secretMixinFields1[0].Descriptor()
	// secret.DefaultMetadata holds the default value on creation for the metadata field.
	secret.DefaultMetadata = secretDescMetadata.Default.(map[string]string)
	// secretDescName is the schema descriptor for name field.
	secretDescName := secretFields[1].Descriptor()
	// secret.NameValidator is a validator for the "name" field. It is called by the builders before save.
	secret.NameValidator = secretDescName.Validators[0].(func(string) error)
	// secretDescType is the schema descriptor for type field.
	secretDescType := secretFields[2].Descriptor()
	// secret.DefaultType holds the default value on creation for the type field.
	secret.DefaultType = types.SecretType(secretDescType.Default.(string))
	// secret.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	secret.TypeValidator = secretDescType.Validators[0].(func(string) error)
	// secretDescProvider is the schema descriptor for provider field.
	secretDescProvider := secretFields[3].Descriptor()
	// secret.DefaultProvider holds the default value on creation for the provider field.
	secret.DefaultProvider = types.SecretProvider(secretDescProvider.Default.(string))
	// secret.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	secret.ProviderValidator = secretDescProvider.Validators[0].(func(string) error)
	// secretDescValue is the schema descriptor for value field.
	secretDescValue := secretFields[4].Descriptor()
	// secret.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	secret.ValueValidator = secretDescValue.Validators[0].(func(string) error)
	// secretDescPrefix is the schema descriptor for prefix field.
	secretDescPrefix := secretFields[5].Descriptor()
	// secret.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	secret.PrefixValidator = secretDescPrefix.Validators[0].(func(string) error)
	// secretDescID is the schema descriptor for id field.
	secretDescID := secretFields[0].Descriptor()
	// secret.DefaultID holds the default value on creation for the id field.
	secret.DefaultID = secretDescID.Default.(func() string)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userMixinFields0[0].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescMetadata is the schema descriptor for metadata field.
	userDescMetadata := userMixinFields1[0].Descriptor()
	// user.DefaultMetadata holds the default value on creation for the metadata field.
	user.DefaultMetadata = userDescMetadata.Default.(map[string]string)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
