// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/nashikdarshan/ent/itinerary"
	"github.com/omkar273/nashikdarshan/ent/place"
	"github.com/omkar273/nashikdarshan/ent/visit"
)

// Visit is the model entity for the Visit schema.
type Visit struct {
	config `json:"-"`
	// ID of the ent.
	// Unique visit identifier with prefix visit_
	ID string `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// FK to parent itinerary
	ItineraryID string `json:"itinerary_id,omitempty"`
	// FK to place being visited
	PlaceID string `json:"place_id,omitempty"`
	// Position in itinerary (0-indexed)
	SequenceOrder int `json:"sequence_order,omitempty"`
	// Expected time to spend at this place
	PlannedDurationMinutes int `json:"planned_duration_minutes,omitempty"`
	// Distance from previous visit in route
	DistanceFromPreviousKm *float64 `json:"distance_from_previous_km,omitempty"`
	// Travel time from previous visit
	TravelTimeFromPreviousMinutes *int `json:"travel_time_from_previous_minutes,omitempty"`
	// Transport mode for this leg: WALKING, DRIVING, TAXI
	TransportMode *string `json:"transport_mode,omitempty"`
	// User notes for this visit
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VisitQuery when eager-loading is set.
	Edges        VisitEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VisitEdges holds the relations/edges for other nodes in the graph.
type VisitEdges struct {
	// Itinerary holds the value of the itinerary edge.
	Itinerary *Itinerary `json:"itinerary,omitempty"`
	// Place holds the value of the place edge.
	Place *Place `json:"place,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ItineraryOrErr returns the Itinerary value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VisitEdges) ItineraryOrErr() (*Itinerary, error) {
	if e.Itinerary != nil {
		return e.Itinerary, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: itinerary.Label}
	}
	return nil, &NotLoadedError{edge: "itinerary"}
}

// PlaceOrErr returns the Place value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VisitEdges) PlaceOrErr() (*Place, error) {
	if e.Place != nil {
		return e.Place, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: place.Label}
	}
	return nil, &NotLoadedError{edge: "place"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Visit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case visit.FieldDistanceFromPreviousKm:
			values[i] = new(sql.NullFloat64)
		case visit.FieldSequenceOrder, visit.FieldPlannedDurationMinutes, visit.FieldTravelTimeFromPreviousMinutes:
			values[i] = new(sql.NullInt64)
		case visit.FieldID, visit.FieldStatus, visit.FieldCreatedBy, visit.FieldUpdatedBy, visit.FieldItineraryID, visit.FieldPlaceID, visit.FieldTransportMode, visit.FieldNotes:
			values[i] = new(sql.NullString)
		case visit.FieldCreatedAt, visit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Visit fields.
func (_m *Visit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case visit.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case visit.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case visit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case visit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case visit.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case visit.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case visit.FieldItineraryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field itinerary_id", values[i])
			} else if value.Valid {
				_m.ItineraryID = value.String
			}
		case visit.FieldPlaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place_id", values[i])
			} else if value.Valid {
				_m.PlaceID = value.String
			}
		case visit.FieldSequenceOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence_order", values[i])
			} else if value.Valid {
				_m.SequenceOrder = int(value.Int64)
			}
		case visit.FieldPlannedDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field planned_duration_minutes", values[i])
			} else if value.Valid {
				_m.PlannedDurationMinutes = int(value.Int64)
			}
		case visit.FieldDistanceFromPreviousKm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field distance_from_previous_km", values[i])
			} else if value.Valid {
				_m.DistanceFromPreviousKm = new(float64)
				*_m.DistanceFromPreviousKm = value.Float64
			}
		case visit.FieldTravelTimeFromPreviousMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field travel_time_from_previous_minutes", values[i])
			} else if value.Valid {
				_m.TravelTimeFromPreviousMinutes = new(int)
				*_m.TravelTimeFromPreviousMinutes = int(value.Int64)
			}
		case visit.FieldTransportMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transport_mode", values[i])
			} else if value.Valid {
				_m.TransportMode = new(string)
				*_m.TransportMode = value.String
			}
		case visit.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Visit.
// This includes values selected through modifiers, order, etc.
func (_m *Visit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItinerary queries the "itinerary" edge of the Visit entity.
func (_m *Visit) QueryItinerary() *ItineraryQuery {
	return NewVisitClient(_m.config).QueryItinerary(_m)
}

// QueryPlace queries the "place" edge of the Visit entity.
func (_m *Visit) QueryPlace() *PlaceQuery {
	return NewVisitClient(_m.config).QueryPlace(_m)
}

// Update returns a builder for updating this Visit.
// Note that you need to call Visit.Unwrap() before calling this method if this Visit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Visit) Update() *VisitUpdateOne {
	return NewVisitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Visit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Visit) Unwrap() *Visit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Visit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Visit) String() string {
	var builder strings.Builder
	builder.WriteString("Visit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("itinerary_id=")
	builder.WriteString(_m.ItineraryID)
	builder.WriteString(", ")
	builder.WriteString("place_id=")
	builder.WriteString(_m.PlaceID)
	builder.WriteString(", ")
	builder.WriteString("sequence_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SequenceOrder))
	builder.WriteString(", ")
	builder.WriteString("planned_duration_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlannedDurationMinutes))
	builder.WriteString(", ")
	if v := _m.DistanceFromPreviousKm; v != nil {
		builder.WriteString("distance_from_previous_km=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TravelTimeFromPreviousMinutes; v != nil {
		builder.WriteString("travel_time_from_previous_minutes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TransportMode; v != nil {
		builder.WriteString("transport_mode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Visits is a parsable slice of Visit.
type Visits []*Visit
